<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Renders saved block documents and manages their generated stylesheets.
 */
final class Code_To_Block_Renderer {
	const ASSET_DIRECTORY = 'code-to-block';

	/**
	 * Renders imported html/body identity for the dedicated frontend document.
	 * Executable and style attributes remain in their isolated asset systems.
	 *
	 * @param array  $document       Sanitized builder document.
	 * @param string $scope          html or body.
	 * @param array  $base_attributes WordPress-owned attributes to merge.
	 * @return string
	 */
	public static function render_imported_page_root_attributes( $document, $scope, $base_attributes = array() ) {
		$scope = 'html' === $scope ? 'html' : 'body';
		$assets = isset( $document['imported_assets'] ) ? self::object_to_array( $document['imported_assets'] ) : array();
		$page_meta = isset( $assets['page_meta'] ) ? self::object_to_array( $assets['page_meta'] ) : array();
		$key = $scope . '_attributes';
		$imported = isset( $page_meta[ $key ] ) ? self::object_to_array( $page_meta[ $key ] ) : array();
		$attributes = is_array( $base_attributes ) ? $base_attributes : array();
		foreach ( $imported as $name => $value ) {
			$name = is_string( $name ) ? strtolower( $name ) : '';
			if (
				! preg_match( '/^(?:class|id|lang|dir|title|role|hidden|tabindex|(?:aria|data)-[a-z0-9_.:-]+)$/', $name ) ||
				0 === strpos( $name, 'data-ctb-' ) ||
				( ! is_string( $value ) && ! is_bool( $value ) )
			) {
				continue;
			}
			if ( 'class' === $name ) {
				$attributes['class'] = trim( ( isset( $attributes['class'] ) ? $attributes['class'] : '' ) . ' ' . $value );
			} else {
				$attributes[ $name ] = $value;
			}
		}
		$html = '';
		foreach ( $attributes as $name => $value ) {
			if ( true === $value ) {
				$html .= ' ' . esc_attr( $name );
			} elseif ( is_string( $value ) && '' !== $value ) {
				$html .= ' ' . esc_attr( $name ) . '="' . esc_attr( $value ) . '"';
			}
		}
		return $html;
	}

	/**
	 * Base URL used while rendering one imported document.
	 *
	 * @var string
	 */
	private static $resource_base = '';

	/**
	 * Produces the public markup for a block document.
	 *
	 * @param array $document Sanitized block document.
	 * @param int   $post_id  Owning post ID.
	 * @return string
	 */
	public static function render_document( $document, $post_id ) {
		if ( ! is_array( $document ) || ! isset( $document['root'] ) ) {
			return '';
		}

		$index                  = 0;
		$previous_resource_base = self::$resource_base;
		self::$resource_base    = self::imported_resource_base( $document );
		Code_To_Block_Shortcodes::register_for_post( (int) $post_id );
		try {
			$markup = sprintf(
				'<div id="ctb-page-%1$d" class="ctb-page" data-ctb-post-id="%1$d">%2$s</div>',
				(int) $post_id,
				self::render_block( $document['root'], $index, (int) $post_id )
			);
		} finally {
			Code_To_Block_Shortcodes::unregister_for_post( (int) $post_id );
			self::$resource_base = $previous_resource_base;
		}
		return $markup;
	}

	/**
	 * Produces the complete scoped stylesheet for a block document.
	 *
	 * @param array $document Sanitized block document.
	 * @param int   $post_id  Owning post ID.
	 * @return string
	 */
	public static function generate_css( $document, $post_id ) {
		if ( ! is_array( $document ) || ! isset( $document['root'] ) ) {
			return '';
		}

		$previous_resource_base = self::$resource_base;
		self::$resource_base    = self::imported_resource_base( $document );
		$rules                  = array(
			'base'       => array(),
			'tablet'     => array(),
			'mobile'     => array(),
			'v3_tablet'  => array(),
			'v3_mobile'  => array(),
		);
		$index = 0;
		self::collect_css_rules( $document['root'], (int) $post_id, $index, $rules );

		$css = sprintf(
			"/* Generated by Code to Block. Do not edit. */\n#ctb-page-%1\$d,#ctb-page-%1\$d *{box-sizing:border-box;}\n#ctb-page-%1\$d>.ctb-block-0{width:100%%;}\n:where(#ctb-page-%1\$d) :where(.ctb-image-root){margin:0;}\n:where(#ctb-page-%1\$d) :where(.ctb-image-link){display:block;}\n:where(#ctb-page-%1\$d) :where(.ctb-image-media){display:block;max-width:100%%;}\n",
			(int) $post_id
		);
		// Protected focus indicator: visible by default for keyboard users, not trivially stripped
		$css .= sprintf( "#ctb-page-%d [data-ctb-actions]:focus-visible,#ctb-page-%d a:focus-visible,#ctb-page-%d button:focus-visible{outline:2px solid #6558d3;outline-offset:2px;}\n", (int) $post_id, (int) $post_id, (int) $post_id );
		$css .= sprintf( "@keyframes ctb-reveal-%1\$d{from{opacity:0;transform:translateY(var(--ctb-reveal-y,30px));}to{opacity:1;transform:none;}}\n#ctb-page-%1\$d [data-ctb-css-animation=\"reveal\"]{animation:ctb-reveal-%1\$d var(--ctb-reveal-duration,.6s) ease-out var(--ctb-reveal-delay,0s) both;}\n@media (prefers-reduced-motion:reduce){#ctb-page-%1\$d [data-ctb-css-animation=\"reveal\"]{animation:none;}}\n", (int) $post_id );
		$css .= sprintf( "@keyframes ctb-shimmer{0%%{background-position:-1000px 0;}100%%{background-position:1000px 0;}}\n#ctb-page-%1\$d .ctb-skeleton{background:#e2e2e2;background-image:linear-gradient(90deg,#e2e2e2 0px,#f0f0f0 100px,#e2e2e2 200px);background-size:1000px 100%%;animation:ctb-shimmer 2s infinite linear;border-radius:4px;opacity:0.6;}\n#ctb-page-%1\$d .ctb-skeleton-bar{height:20px;margin-bottom:8px;}\n#ctb-page-%1\$d .ctb-skeleton-image{height:200px;width:100%%;}\n#ctb-page-%1\$d .ctb-skeleton-link{height:40px;width:120px;border-radius:20px;}\n", (int) $post_id );
		$css .= sprintf( "#ctb-page-%1\$d [data-ctb-lazy-media]{background-color:#e9ebf3;background-image:linear-gradient(90deg,#e9ebf3 0,#f6f7fb 42%%,#e9ebf3 82%%);background-size:220%% 100%%;animation:ctb-shimmer 1.6s linear infinite;transition:opacity .24s ease,background-color .24s ease;}\n#ctb-page-%1\$d [data-ctb-lazy-media].is-loaded,#ctb-page-%1\$d [data-ctb-lazy-media].is-error{background-image:none;animation:none;}\n@media (prefers-reduced-motion:reduce){#ctb-page-%1\$d [data-ctb-lazy-media]{animation:none;transition:none;}}\n", (int) $post_id );
		$token_declarations = self::design_token_declarations( isset( $document['design_tokens'] ) ? $document['design_tokens'] : array() );
		if ( '' !== $token_declarations ) {
			$css .= '#ctb-page-' . (int) $post_id . '{' . $token_declarations . "}\n";
		}
		$css .= self::imported_stylesheet_css( $document );
		$imported_token_declarations = self::imported_token_declarations( $document );
		if ( '' !== $imported_token_declarations ) {
			$css .= '.ctb-import-scope{' . $imported_token_declarations . "}\n";
		}
		$css .= implode( "\n", $rules['base'] );
		if ( ! empty( $rules['tablet'] ) ) {
			$css .= "\n@media (max-width:1024px){\n" . implode( "\n", $rules['tablet'] ) . "\n}";
		}
		if ( ! empty( $rules['mobile'] ) ) {
			$css .= "\n@media (max-width:767px){\n" . implode( "\n", $rules['mobile'] ) . "\n}";
		}
		if ( ! empty( $rules['v3_tablet'] ) ) {
			$css .= "\n@media (max-width:768px){\n" . implode( "\n", $rules['v3_tablet'] ) . "\n}";
		}
		if ( ! empty( $rules['v3_mobile'] ) ) {
			$css .= "\n@media (max-width:390px){\n" . implode( "\n", $rules['v3_mobile'] ) . "\n}";
		}

		self::$resource_base = $previous_resource_base;
		return $css . "\n";
	}

	/**
	 * Collects the declarations emitted by the frontend CSS renderer per block.
	 *
	 * @param array $document Sanitized, resolved block document.
	 * @return array
	 */
	public static function style_snapshot( $document ) {
		if ( ! is_array( $document ) || ! isset( $document['root'] ) ) {
			return array();
		}

		$snapshot = array();
		self::collect_style_snapshot( $document['root'], $snapshot );
		return $snapshot;
	}

	/**
	 * Writes a per-post stylesheet to the uploads directory.
	 *
	 * @param int   $post_id  Owning post ID.
	 * @param array $document Sanitized block document.
	 * @return array|WP_Error Asset path and URL, or an error.
	 */
	public static function write_stylesheet( $post_id, $document ) {
		$css   = self::generate_css( $document, $post_id );
		$asset = self::get_asset_location( $post_id, $document, true, $css );
		if ( is_wp_error( $asset ) ) {
			return $asset;
		}
		if ( file_exists( $asset['path'] ) ) {
			// Protect an asset selected by an in-flight save from grace-period cleanup.
			@touch( $asset['path'] );
			return $asset;
		}

		$temp_path = tempnam( $asset['directory'], 'ctb-' );
		if ( false === $temp_path ) {
			return self::filesystem_error( 'The temporary stylesheet could not be created.' );
		}

		$written = file_put_contents( $temp_path, $css, LOCK_EX );
		if ( false === $written || strlen( $css ) !== $written ) {
			@unlink( $temp_path );
			return self::filesystem_error( 'The generated stylesheet could not be written.' );
		}

		if ( ! @rename( $temp_path, $asset['path'] ) ) {
			// PHP on Windows cannot replace an existing file with rename().
			if ( file_exists( $asset['path'] ) ) {
				@unlink( $asset['path'] );
			}
			if ( ! @rename( $temp_path, $asset['path'] ) ) {
				@unlink( $temp_path );
				return self::filesystem_error( 'The generated stylesheet could not be installed.' );
			}
		}

		return $asset;
	}

	/**
	 * Returns a generated asset when it exists.
	 *
	 * @param int $post_id Owning post ID.
	 * @return array|WP_Error
	 */
	public static function get_stylesheet( $post_id, $document ) {
		return self::get_asset_location( $post_id, $document, false );
	}

	/**
	 * Retires superseded assets, preserving them for cached or in-flight pages.
	 *
	 * @param int    $post_id     Owning post ID.
	 * @param string $current_path Current stylesheet path.
	 */
	public static function retire_stale_stylesheets( $post_id, $current_path ) {
		$uploads = wp_upload_dir();
		if ( ! empty( $uploads['error'] ) ) {
			return;
		}

		$directory = trailingslashit( $uploads['basedir'] ) . self::ASSET_DIRECTORY;
		$paths     = glob( trailingslashit( $directory ) . 'ctb-page-' . (int) $post_id . '-*.css' );
		$cutoff    = time() - DAY_IN_SECONDS;
		foreach ( is_array( $paths ) ? $paths : array() as $path ) {
			$marker = $path . '.obsolete';
			if ( $path === $current_path ) {
				if ( file_exists( $marker ) ) {
					@unlink( $marker );
				}
				continue;
			}
			if ( file_exists( $marker ) && filemtime( $marker ) < $cutoff ) {
				@unlink( $path );
				@unlink( $marker );
			} elseif ( ! file_exists( $marker ) ) {
				@touch( $marker );
			}
		}
	}

	/**
	 * Removes a generated per-post stylesheet.
	 *
	 * @param int $post_id Owning post ID.
	 */
	public static function delete_stylesheet( $post_id ) {
		$uploads = wp_upload_dir();
		if ( ! empty( $uploads['error'] ) ) {
			return;
		}

		$directory = trailingslashit( $uploads['basedir'] ) . self::ASSET_DIRECTORY;
		$paths     = glob( trailingslashit( $directory ) . 'ctb-page-' . (int) $post_id . '-*.css' );
		foreach ( is_array( $paths ) ? $paths : array() as $path ) {
			@unlink( $path );
			if ( file_exists( $path . '.obsolete' ) ) {
				@unlink( $path . '.obsolete' );
			}
		}
		$legacy_path = trailingslashit( $directory ) . 'ctb-page-' . (int) $post_id . '.css';
		if ( file_exists( $legacy_path ) ) {
			@unlink( $legacy_path );
		}
	}

	/**
	 * @param array $block Sanitized block.
	 * @param int   $index   Traversal index.
	 * @param int   $post_id Owning page.
	 * @return string
	 */
	private static function render_block( $block, &$index, $post_id ) {
		if ( ! is_array( $block ) || empty( $block['tag'] ) ) {
			return '';
		}

		$current_index = $index++;
		$tag           = strtolower( $block['tag'] );
		if ( ! Code_To_Block_Schema::html_tag_is_allowed( $tag ) ) {
			return '';
		}
		if ( ! self::block_is_visible( $block ) ) {
			$index += self::count_rendered_blocks( isset( $block['children'] ) ? $block['children'] : array() );
			return '';
		}

		$attributes          = self::object_to_array( $block['attributes'] );
		$attributes          = is_array( $attributes ) ? $attributes : array();
		$attributes['data-ctb-block-id'] = $block['id'];
		if ( ! empty( $block['element'] ) && is_string( $block['element'] ) ) {
			$attributes['data-ctb-element'] = $block['element'];
			$attributes['data-ctb-part']    = 'root';
		}
		$runtime_actions = self::runtime_actions_for_block( $block );
		if ( ! empty( $runtime_actions ) ) {
			$encoded_actions = wp_json_encode( $runtime_actions, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE );
			if ( false !== $encoded_actions ) {
				$attributes['data-ctb-actions'] = $encoded_actions;
			}
			// Keyboard operability: ensure trigger is focusable and has ARIA
			if ( ! isset( $attributes['tabindex'] ) ) {
				// Buttons/links are natively focusable; divs/spans need tabindex
				if ( ! in_array( $tag, array( 'button', 'a', 'input', 'select', 'textarea' ), true ) ) {
					$attributes['tabindex'] = '0';
					if ( ! isset( $attributes['role'] ) ) {
						$attributes['role'] = 'button';
					}
				}
			}
			// For toggle-visibility, set aria-expanded false initially; aria-haspopup hints dropdown
			$has_toggle = false;
			foreach ( $runtime_actions as $ra ) {
				if ( 'toggle-visibility' === $ra['behavior'] || 'show' === $ra['behavior'] || 'hide' === $ra['behavior'] ) {
					$has_toggle = true;
					break;
				}
			}
			if ( $has_toggle ) {
				if ( ! isset( $attributes['aria-expanded'] ) ) {
					$attributes['aria-expanded'] = 'false';
				}
				if ( ! isset( $attributes['aria-haspopup'] ) ) {
					$attributes['aria-haspopup'] = 'true';
				}
			}
		}
		$animation_actions = self::animation_actions_for_block( $block );
		if ( ! empty( $animation_actions ) ) {
			$encoded_animations = wp_json_encode( $animation_actions, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE );
			if ( false !== $encoded_animations ) {
				$attributes['data-ctb-animations'] = $encoded_animations;
			}
		}
		$css_animations = self::css_animation_actions_for_block( $block );
		if ( ! empty( $css_animations ) ) {
			$params = $css_animations[0]['params'];
			if ( $params['target_block_id'] === $block['id'] ) {
				$attributes['data-ctb-css-animation'] = 'reveal';
			}
		}
		// Icon handling: decorative images with empty alt should be hidden from screen readers already via alt=""; ensure presentation role not needed.
		// Functional icon-only buttons (button tag with no text, only image) should have aria-label via checker, not auto-guessed here.
		$existing_class      = isset( $attributes['class'] ) && is_string( $attributes['class'] ) ? $attributes['class'] : '';
		$existing_class      = preg_replace( '/(?:^|\s)ctb-block(?:-\d+)?(?=\s|$)/', '', $existing_class );
		$stable_class = ! empty( $block['element'] ) ? ' ' . self::stable_element_class( $block['id'] ) : '';
		$attributes['class'] = trim( $existing_class . ' ctb-block ctb-block-' . $current_index . $stable_class );
		$children = '';
		$is_saved_component = isset( $block['meta']['saved_component_id'] );
		$is_dynamic = ! empty( $block['is_dynamic'] ) && ! empty( $block['dynamic_source'] );
		$button_render_model = self::button_render_model( $block, $attributes );
		$form_field_render_model = self::form_field_render_model( $block, $attributes );
		$image_render_model  = self::image_render_model( $block );
		$text_render_model   = self::text_render_model( $block );
		
		if ( $is_dynamic ) {
			$dynamic_data = self::get_dynamic_data( $block['dynamic_source'], $post_id );
			if ( 'img' === $tag ) {
				if ( ! empty( $dynamic_data['url'] ) ) {
					$attributes['src'] = $dynamic_data['url'];
				}
				if ( isset( $dynamic_data['srcset'] ) ) {
					$attributes['srcset'] = $dynamic_data['srcset'];
				}
				if ( isset( $dynamic_data['alt'] ) ) {
					$attributes['alt'] = $dynamic_data['alt'];
				}
			}
		}
		$performance = isset( $block['performance'] ) ? self::object_to_array( $block['performance'] ) : array();
		$lazy_media =
			( ! empty( $performance['lazy_load'] ) && in_array( $tag, array( 'img', 'iframe' ), true ) ) ||
			( 'img' === $tag && ! empty( $performance['image_lazy_load'] ) );
		if ( $lazy_media ) {
			$attributes['loading'] = 'lazy';
			$attributes['data-ctb-lazy-media'] = 'true';
			$attributes['class'] = trim( ( isset( $attributes['class'] ) ? $attributes['class'] : '' ) . ' ctb-lazy-media' );
			if ( 'img' === $tag ) {
				$attributes['decoding'] = 'async';
			}
		}
		if ( null !== $image_render_model ) {
			return self::render_image_element( $attributes, $image_render_model );
		}
		
		$attribute_html = self::render_attributes( $tag, $attributes );

		if ( in_array( $tag, Code_To_Block_Schema::VOID_TAGS, true ) ) {
			return '<' . $tag . $attribute_html . '>';
		}

		try {
			if ( 'woocommerce_cart' === $block['type'] ) {
				$children = self::get_woocommerce_block_markup( 'cart' );
			} elseif ( 'woocommerce_checkout' === $block['type'] ) {
				$children = self::get_woocommerce_block_markup( 'checkout' );
			} elseif ( 'woocommerce_product' === $block['type'] ) {
				$product_id = isset( $attributes['data-product-id'] ) ? (int) $attributes['data-product-id'] : 0;
				if ( ! $product_id && in_array( get_post_type( $post_id ), array( 'product', 'product_variation' ), true ) ) {
					$product_id = $post_id;
				}
				$wc_product = $product_id && function_exists( 'wc_get_product' ) ? wc_get_product( $product_id ) : false;
				if ( ! $wc_product ) {
					$children = '<p class="ctb-product-empty">Select a valid WooCommerce product.</p>';
				} else {
					foreach ( $block['children'] as $child ) {
						$child = self::object_to_array( $child );
						if ( isset( $child['kind'] ) && 'text' === $child['kind'] ) {
							$children .= Code_To_Block_Shortcodes::render_text( $child['value'], $product_id );
						} else {
							$children .= self::render_block( $child, $index, $product_id );
						}
					}
					if ( 'true' === ( isset( $attributes['data-show-variations'] ) ? $attributes['data-show-variations'] : '' ) ) {
						$children .= Code_To_Block_Commerce::variation_selector( $wc_product );
					}
				}
			} elseif ( 'woocommerce_product_grid' === $block['type'] ) {
				// Grid loops products; children is template for one item. Render grid wrapper + repeated items.
				$template_start_index = $index;
				$template_block_count = self::count_rendered_blocks( $block['children'] );
				$grid_limit = isset( $attributes['data-grid-limit'] ) ? max( 1, min( 12, (int) $attributes['data-grid-limit'] ) ) : 6;
				$grid_products = array();
				if ( function_exists( 'wc_get_products' ) ) {
					$query_args = array( 'limit' => $grid_limit, 'status' => 'publish', 'orderby' => 'date', 'order' => 'DESC' );
					if ( isset( $attributes['data-product-category'] ) && '' !== trim( $attributes['data-product-category'] ) ) {
						$query_args['category'] = array( sanitize_text_field( $attributes['data-product-category'] ) );
					}
					$grid_products = wc_get_products( $query_args );
				}
				if ( empty( $grid_products ) ) {
					$children = '<p class="ctb-product-grid-empty">No products found.</p>';
				} else {
					$grid_items = '';
					foreach ( $grid_products as $grid_product ) {
						$item_index = $template_start_index;
						$grid_product_id = $grid_product->get_id();
						$item_inner = '';
						if ( empty( $block['children'] ) ) {
							$img_data = self::get_dynamic_data( 'wc_product_image', $grid_product_id );
							$title_data = self::get_dynamic_data( 'wc_product_title', $grid_product_id );
							$price_data = self::get_dynamic_data( 'wc_product_price', $grid_product_id );
							$img_html = ! empty( $img_data['url'] ) ? '<img src="' . esc_url( $img_data['url'] ) . '" alt="' . esc_attr( $img_data['alt'] ) . '" style="width:100%;height:auto;">' : '';
							$grid_items .= '<li class="product type-product status-publish ctb-product-grid-item" data-product-id="' . (int) $grid_product_id . '">' . $img_html . '<h3>' . $title_data['html'] . '</h3><div>' . $price_data['html'] . '</div></li>';
						} else {
							foreach ( $block['children'] as $child ) {
								$child = self::object_to_array( $child );
								if ( isset( $child['kind'] ) && 'text' === $child['kind'] ) {
									$item_inner .= Code_To_Block_Shortcodes::render_text( $child['value'], $grid_product_id );
								} else {
								$item_inner .= self::render_block( $child, $item_index, $grid_product_id );
								}
							}
							$grid_items .= '<li class="product type-product status-publish ctb-product-grid-item" data-product-id="' . (int) $grid_product_id . '">' . $item_inner . '</li>';
						}
					}
					$columns = min( 4, max( 1, $grid_limit ) );
					$children = '<ul class="products columns-' . $columns . ' ctb-product-grid">' . $grid_items . '</ul>';
				}
				$index = $template_start_index + $template_block_count;
			} elseif ( 'form' === $block['type'] && empty( $block['meta']['imported_native_html'] ) ) {
				$submission = isset( $attributes['data-submission'] ) ? $attributes['data-submission'] : 'native';
				$submit_label = isset( $attributes['data-submit-label'] ) && is_string( $attributes['data-submit-label'] )
					? trim( $attributes['data-submit-label'] )
					: 'Submit';
				if ( '' === $submit_label ) {
					$submit_label = 'Submit';
				}
				unset( $attributes['data-submit-label'] );
				if ( 'external' === $submission && ! empty( $attributes['data-external-shortcode'] ) ) {
					$shortcode = trim( $attributes['data-external-shortcode'] );
					$allowed_shortcodes = array( 'contact-form-7', 'wpforms', 'formidable', 'gravityform', 'ninja_form' );
					$shortcode_pattern = '/^' . get_shortcode_regex( $allowed_shortcodes ) . '$/s';
					if ( preg_match( $shortcode_pattern, $shortcode, $shortcode_match ) && in_array( strtolower( $shortcode_match[2] ), $allowed_shortcodes, true ) ) {
						$children = do_shortcode( $shortcode );
					} else {
						$children = '<p class="ctb-form-external-note">External form: ' . esc_html( $shortcode ) . '</p>';
					}
					// External plugins render their own form; avoid invalid nested form markup.
					$tag = 'div';
					$attributes['class'] = trim( $attributes['class'] . ' ctb-form-external' );
				} else {
					// Native form: render children fields + honeypot + timestamp + submit
					$fields_html = '';
					foreach ( $block['children'] as $child ) {
						$child = self::object_to_array( $child );
						if ( isset( $child['kind'] ) && 'text' === $child['kind'] ) {
							$fields_html .= Code_To_Block_Shortcodes::render_text( $child['value'], $post_id );
						} else {
							$fields_html .= self::render_block( $child, $index, $post_id );
						}
					}
					$honeypot_name = '_ctb_hp_' . substr( md5( $block['id'] ), 0, 8 );
					$timestamp = time();
					$action_url = rest_url( 'code-to-block/v1/forms/' . (int) $post_id . '/submit' );
					$email_to = isset( $attributes['data-email-to'] ) ? $attributes['data-email-to'] : get_option( 'admin_email' );
					$submission_token = Code_To_Block_Forms::create_submission_token( $post_id, $block['id'], $timestamp );
					$children = '<div class="ctb-form-fields">' . $fields_html . '</div>'
						. '<div style="position:absolute;left:-9999px;top:auto;width:1px;height:1px;overflow:hidden;" aria-hidden="true"><label>Leave this field empty<input type="text" name="' . esc_attr( $honeypot_name ) . '" tabindex="-1" autocomplete="off"></label></div>'
						. '<input type="hidden" name="_ctb_form_id" value="' . esc_attr( $block['id'] ) . '">'
						. '<input type="hidden" name="_ctb_timestamp" value="' . esc_attr( $timestamp ) . '">'
						. '<input type="hidden" name="_ctb_submission_token" value="' . esc_attr( $submission_token ) . '">'
						. '<input type="hidden" name="_ctb_honeypot_name" value="' . esc_attr( $honeypot_name ) . '">'
						. '<div class="ctb-form-actions"><button type="submit" class="ctb-form-submit">' . esc_html( $submit_label ) . '</button></div>'
						. '<div class="ctb-form-message" role="status" aria-live="polite" style="margin-top:12px;"></div>';
					// Wrap with form tag attributes
					$attributes['method'] = 'post';
					$attributes['action'] = $action_url;
					if ( strpos( $fields_html, 'type="file"' ) !== false ) {
						$attributes['enctype'] = 'multipart/form-data';
					}
					$attributes['class'] = trim( ( isset( $attributes['class'] ) ? $attributes['class'] : '' ) . ' ctb-form' );
					$attributes['data-email-to'] = $email_to;
					$attributes['data-form-id'] = $block['id'];
				}
				unset( $attributes['data-email-to'] );
			} elseif ( null !== $form_field_render_model ) {
				$children = self::render_form_field( $form_field_render_model );
			} elseif ( 'form_field' === $block['type'] && empty( $block['meta']['imported_native_html'] ) ) {
				$field_type = isset( $attributes['data-field-type'] ) ? $attributes['data-field-type'] : 'text';
				$field_label = isset( $attributes['data-field-label'] ) ? $attributes['data-field-label'] : '';
				$field_name = isset( $attributes['data-field-name'] ) ? $attributes['data-field-name'] : $block['id'];
				$field_placeholder = isset( $attributes['data-field-placeholder'] ) ? $attributes['data-field-placeholder'] : '';
				$field_required = ! empty( $attributes['data-field-required'] );
				$field_options = isset( $attributes['data-field-options'] ) ? $attributes['data-field-options'] : '';
				$required_attr = $field_required ? ' required aria-required="true"' : '';
				$label_html = $field_label ? '<label for="' . esc_attr( $block['id'] . '-input' ) . '">' . esc_html( $field_label ) . ( $field_required ? ' <span aria-hidden="true">*</span>' : '' ) . '</label>' : '';
				if ( 'textarea' === $field_type ) {
					$children = $label_html . '<textarea id="' . esc_attr( $block['id'] . '-input' ) . '" name="' . esc_attr( $field_name ) . '" placeholder="' . esc_attr( $field_placeholder ) . '"' . $required_attr . ' rows="4"></textarea>';
				} elseif ( 'select' === $field_type ) {
					$options = array_map( 'trim', explode( ',', $field_options ) );
					$options_html = '<option value="">' . esc_html( $field_placeholder ? $field_placeholder : 'Select...' ) . '</option>';
					foreach ( $options as $opt ) {
						if ( '' === $opt ) continue;
						$options_html .= '<option value="' . esc_attr( $opt ) . '">' . esc_html( $opt ) . '</option>';
					}
					$children = $label_html . '<select id="' . esc_attr( $block['id'] . '-input' ) . '" name="' . esc_attr( $field_name ) . '"' . $required_attr . '>' . $options_html . '</select>';
				} elseif ( 'checkbox' === $field_type || 'radio' === $field_type ) {
					$options = array_map( 'trim', explode( ',', $field_options ) );
					if ( empty( $options[0] ) ) $options = array( $field_label ? $field_label : 'Option' );
					$group_html = '';
					foreach ( $options as $opt ) {
						if ( '' === $opt ) continue;
						$group_html .= '<label style="display:flex;gap:6px;align-items:center;"><input type="' . esc_attr( $field_type ) . '" name="' . esc_attr( $field_name ) . ( 'checkbox' === $field_type ? '[]' : '' ) . '" value="' . esc_attr( $opt ) . '"' . $required_attr . '> ' . esc_html( $opt ) . '</label>';
					}
					$children = ( $field_label && count( $options ) > 1 ? '<fieldset><legend>' . esc_html( $field_label ) . '</legend>' . $group_html . '</fieldset>' : $group_html );
				} elseif ( 'file' === $field_type ) {
					$children = $label_html . '<input id="' . esc_attr( $block['id'] . '-input' ) . '" type="file" name="' . esc_attr( $field_name ) . '"' . $required_attr . '>';
				} else {
					$type = in_array( $field_type, array( 'text', 'email', 'tel', 'url', 'number' ), true ) ? $field_type : 'text';
					$children = $label_html . '<input id="' . esc_attr( $block['id'] . '-input' ) . '" type="' . esc_attr( $type ) . '" name="' . esc_attr( $field_name ) . '" placeholder="' . esc_attr( $field_placeholder ) . '"' . $required_attr . '>';
				}
				$children = '<div class="ctb-form-field" data-field-type="' . esc_attr( $field_type ) . '">' . $children . '</div>';
			} elseif ( null !== $button_render_model ) {
				$label_children = '';
				if ( '' !== $button_render_model['loading_label'] ) {
					$index += self::count_rendered_blocks( isset( $block['children'] ) ? $block['children'] : array() );
					$label_children = esc_html( $button_render_model['loading_label'] );
				} elseif ( $is_dynamic ) {
					$dynamic_data = self::get_dynamic_data( $block['dynamic_source'], $post_id );
					$label_children = isset( $dynamic_data['html'] ) ? $dynamic_data['html'] : '';
				} else {
					foreach ( $block['children'] as $child ) {
						$child = self::object_to_array( $child );
						if ( isset( $child['kind'] ) && 'text' === $child['kind'] ) {
							$label_children .= Code_To_Block_Shortcodes::render_text( $child['value'], $post_id );
						} else {
							$label_children .= self::render_block( $child, $index, $post_id );
						}
					}
				}

				$target_children = array(
					'label' => '<span data-ctb-part="label">' . $label_children . '</span>',
					'icon' => '<span class="' . esc_attr( trim( 'ctb-button-icon ' . $button_render_model['icon'] ) ) . '" data-ctb-part="icon" aria-hidden="true"></span>',
					'spinner' => '<span class="ctb-button-spinner" data-ctb-part="spinner" aria-hidden="true">&#8230;</span>',
				);
				foreach ( $button_render_model['parts'] as $part ) {
					$children .= $target_children[ $part ];
				}
			} elseif ( null !== $text_render_model ) {
				$text_children = '';
				if ( $is_dynamic ) {
					$dynamic_data = self::get_dynamic_data( $block['dynamic_source'], $post_id );
					$text_children = isset( $dynamic_data['html'] ) ? $dynamic_data['html'] : '';
				} else {
					foreach ( $block['children'] as $child ) {
						$child = self::object_to_array( $child );
						if ( isset( $child['kind'] ) && 'text' === $child['kind'] ) {
							$text_children .= Code_To_Block_Shortcodes::render_text( $child['value'], $post_id );
						} else {
							$text_children .= self::render_block( $child, $index, $post_id );
						}
					}
				}
				if ( '' !== $text_render_model['href'] ) {
					$children = '<a data-ctb-part="text" href="' . esc_url( $text_render_model['href'] ) . '">' . $text_children . '</a>';
				} else {
					$children = '<span data-ctb-part="text">' . $text_children . '</span>';
				}
			} elseif ( $is_dynamic && 'img' !== $tag ) {
				$dynamic_data = self::get_dynamic_data( $block['dynamic_source'], $post_id );
				$children = $dynamic_data['html'] ?? '';
			} else {
				$child_context_post_id = $post_id;

				foreach ( $block['children'] as $child ) {
					$child = self::object_to_array( $child );
					if ( isset( $child['kind'] ) && 'text' === $child['kind'] ) {
						$children .= ! empty( $block['is_content_slot'] ) && 'rich_text' === ( $block['slot_content_type'] ?? '' )
							? Code_To_Block_Schema::sanitize_rich_text( $child['value'] )
							: Code_To_Block_Shortcodes::render_text( $child['value'], $child_context_post_id );
					} else {
						$children .= self::render_block( $child, $index, $child_context_post_id );
					}
				}
			}
		} catch ( Throwable $error ) {
			if ( ! $is_saved_component ) {
				throw $error;
			}
			$children = esc_html( Code_To_Block_Components::FAILURE_MESSAGE );
		}

		// Some specialized blocks finalize their tag or attributes while rendering.
		$attribute_html = self::render_attributes( $tag, $attributes );
		return '<' . $tag . $attribute_html . '>' . $children . '</' . $tag . '>';
	}

	/**
	 * Resolve the stable target parts for registry-backed button renderers.
	 *
	 * @param array $block      Sanitized block.
	 * @param array $attributes Sanitized HTML attributes.
	 * @return array|null
	 */
	private static function button_render_model( $block, $attributes ) {
		$element_id = isset( $block['element'] ) && is_string( $block['element'] ) ? $block['element'] : '';
		$definition = '' !== $element_id ? Code_To_Block_Registry::get( $element_id ) : null;
		if (
			null === $definition ||
			'button' !== ( isset( $definition['rendererFamily'] ) ? $definition['rendererFamily'] : '' ) ||
			empty( $definition['targets'] ) ||
			! in_array( 'label', $definition['targets'], true )
		) {
			return null;
		}

		$props = isset( $block['props'] ) ? self::object_to_array( $block['props'] ) : array();
		$props = is_array( $props ) ? $props : array();
		$loading =
			self::attribute_is_true( isset( $attributes['aria-busy'] ) ? $attributes['aria-busy'] : false ) ||
			self::attribute_is_true( isset( $attributes['data-ctb-loading'] ) ? $attributes['data-ctb-loading'] : false );
		$icon = isset( $props['icon'] ) && is_string( $props['icon'] ) ? trim( $props['icon'] ) : '';
		$loading_label = $loading && isset( $props['loadingLabel'] ) && is_string( $props['loadingLabel'] )
			? trim( $props['loadingLabel'] )
			: '';

		if ( $loading && in_array( 'spinner', $definition['targets'], true ) ) {
			$parts = array( 'spinner', 'label' );
		} elseif ( '' !== $icon && in_array( 'icon', $definition['targets'], true ) ) {
			$parts = isset( $props['iconPosition'] ) && 'before' === $props['iconPosition']
				? array( 'icon', 'label' )
				: array( 'label', 'icon' );
		} else {
			$parts = array( 'label' );
		}

		return array(
			'icon'          => $icon,
			'loading_label' => $loading_label,
			'parts'         => $parts,
		);
	}

	/**
	 * Resolve registry-backed Form Field props with legacy attributes as fallback.
	 *
	 * @param array $block      Sanitized block.
	 * @param array $attributes Sanitized HTML attributes.
	 * @return array|null
	 */
	private static function form_field_render_model( $block, $attributes ) {
		$element_id = isset( $block['element'] ) && is_string( $block['element'] ) ? $block['element'] : '';
		$definition = '' !== $element_id ? Code_To_Block_Registry::get( $element_id ) : null;
		if (
			'forms/field-group' !== $element_id ||
			null === $definition ||
			'form_field' !== ( isset( $definition['rendererFamily'] ) ? $definition['rendererFamily'] : '' ) ||
			empty( $definition['targets'] ) ||
			! in_array( 'row', $definition['targets'], true ) ||
			! in_array( 'control', $definition['targets'], true )
		) {
			return null;
		}

		$props = isset( $block['props'] ) ? self::object_to_array( $block['props'] ) : array();
		$props = is_array( $props ) ? $props : array();
		$field_type = array_key_exists( 'fieldType', $props ) ? $props['fieldType'] : ( isset( $attributes['data-field-type'] ) ? $attributes['data-field-type'] : 'text' );
		$field_type = is_string( $field_type ) ? strtolower( trim( $field_type ) ) : 'text';
		if ( ! in_array( $field_type, array( 'text', 'email', 'tel', 'url', 'number', 'textarea', 'select', 'checkbox', 'radio', 'file' ), true ) ) {
			$field_type = 'text';
		}
		$field_label = array_key_exists( 'label', $props ) ? $props['label'] : ( isset( $attributes['data-field-label'] ) ? $attributes['data-field-label'] : '' );
		$field_name = array_key_exists( 'name', $props ) ? $props['name'] : ( isset( $attributes['data-field-name'] ) ? $attributes['data-field-name'] : $block['id'] );
		$field_placeholder = array_key_exists( 'placeholder', $props ) ? $props['placeholder'] : ( isset( $attributes['data-field-placeholder'] ) ? $attributes['data-field-placeholder'] : '' );
		$field_help = array_key_exists( 'help', $props ) ? $props['help'] : '';
		$field_required = self::attribute_is_true(
			array_key_exists( 'required', $props ) ? $props['required'] : ( isset( $attributes['data-field-required'] ) ? $attributes['data-field-required'] : false )
		);
		$field_options = array_key_exists( 'options', $props ) ? self::object_to_array( $props['options'] ) : ( isset( $attributes['data-field-options'] ) ? $attributes['data-field-options'] : array() );
		$field_options = is_string( $field_options ) ? explode( ',', $field_options ) : $field_options;
		$field_options = is_array( $field_options ) ? $field_options : array();
		$options = array();
		foreach ( $field_options as $option ) {
			$option = self::object_to_array( $option );
			if ( is_string( $option ) ) {
				$option_label = trim( $option );
				$option_value = $option_label;
			} elseif ( is_array( $option ) ) {
				$option_label = isset( $option['label'] ) && is_string( $option['label'] ) ? trim( $option['label'] ) : '';
				$option_value = isset( $option['value'] ) && is_string( $option['value'] ) ? trim( $option['value'] ) : $option_label;
				if ( '' === $option_label ) {
					$option_label = $option_value;
				}
			} else {
				continue;
			}
			if ( '' !== $option_label ) {
				$options[] = array( 'label' => $option_label, 'value' => $option_value );
			}
		}

		$field_label = is_string( $field_label ) ? trim( $field_label ) : '';
		$field_name = is_string( $field_name ) && '' !== trim( $field_name ) ? trim( $field_name ) : $block['id'];
		$field_placeholder = is_string( $field_placeholder ) ? trim( $field_placeholder ) : '';
		$field_help = is_string( $field_help ) ? trim( $field_help ) : '';
		return array(
			'field_type'  => $field_type,
			'label'       => $field_label,
			'name'        => $field_name,
			'placeholder' => $field_placeholder,
			'help'        => $field_help,
			'required'    => $field_required,
			'options'     => $options,
			'control_id'  => $block['id'] . '-input',
			'label_id'    => $block['id'] . '-label',
			'help_id'     => $block['id'] . '-help',
			'error_id'    => $block['id'] . '-error',
		);
	}

	/**
	 * Render the stable Form Field row and descendant target contract.
	 *
	 * @param array $model Resolved field model.
	 * @return string
	 */
	private static function render_form_field( $model ) {
		$choice_field = in_array( $model['field_type'], array( 'checkbox', 'radio' ), true );
		$required_mark = $model['required']
			? '<span data-ctb-part="requiredMark" aria-hidden="true">*</span>'
			: '';
		$label_tag = $choice_field ? 'span' : 'label';
		$label_attributes = array(
			'id'            => $model['label_id'],
			'data-ctb-part' => 'label',
		);
		if ( ! $choice_field ) {
			$label_attributes['for'] = $model['control_id'];
		}
		$label_html = '<' . $label_tag . self::render_attributes( $label_tag, $label_attributes ) . '>' . esc_html( $model['label'] ) . $required_mark . '</' . $label_tag . '>';

		$common_attributes = array(
			'id'                  => $model['control_id'],
			'name'                => $model['name'],
			'data-ctb-part'       => 'control',
			'required'            => $model['required'],
			'aria-required'       => $model['required'] ? 'true' : false,
			'aria-describedby'    => '' !== $model['help'] ? $model['help_id'] : false,
			'aria-errormessage'   => $model['error_id'],
		);
		if ( 'textarea' === $model['field_type'] ) {
			$control_attributes = array_merge( $common_attributes, array( 'placeholder' => $model['placeholder'], 'rows' => '4' ) );
			$control_html = '<textarea' . self::render_attributes( 'textarea', $control_attributes ) . '></textarea>';
		} elseif ( 'select' === $model['field_type'] ) {
			$options_html = '<option value="">' . esc_html( '' !== $model['placeholder'] ? $model['placeholder'] : 'Select...' ) . '</option>';
			foreach ( $model['options'] as $option ) {
				$options_html .= '<option value="' . esc_attr( $option['value'] ) . '">' . esc_html( $option['label'] ) . '</option>';
			}
			$control_html = '<select' . self::render_attributes( 'select', $common_attributes ) . '>' . $options_html . '</select>';
		} elseif ( $choice_field ) {
			$choice_options = $model['options'];
			if ( empty( $choice_options ) ) {
				$fallback = '' !== $model['label'] ? $model['label'] : 'Option';
				$choice_options = array( array( 'label' => $fallback, 'value' => $fallback ) );
			}
			$choices_html = '';
			foreach ( $choice_options as $choice_index => $option ) {
				$choice_attributes = array_merge(
					$common_attributes,
					array(
						'id'    => $model['control_id'] . '-' . $choice_index,
						'type'  => $model['field_type'],
						'name'  => 'checkbox' === $model['field_type'] ? $model['name'] . '[]' : $model['name'],
						'value' => $option['value'],
					)
				);
				$choices_html .= '<label class="ctb-form-option"><input' . self::render_attributes( 'input', $choice_attributes ) . '><span>' . esc_html( $option['label'] ) . '</span></label>';
			}
			$group_attributes = array(
				'class'           => 'ctb-form-options',
				'role'            => 'group',
				'aria-labelledby' => '' !== $model['label'] ? $model['label_id'] : false,
			);
			$control_html = '<div' . self::render_attributes( 'div', $group_attributes ) . '>' . $choices_html . '</div>';
		} else {
			$control_attributes = array_merge(
				$common_attributes,
				array(
					'type'        => $model['field_type'],
					'placeholder' => 'file' === $model['field_type'] ? false : $model['placeholder'],
				)
			);
			$control_html = '<input' . self::render_attributes( 'input', $control_attributes ) . '>';
		}

		$help_attributes = array(
			'id'            => $model['help_id'],
			'data-ctb-part' => 'help',
			'hidden'        => '' === $model['help'],
		);
		$error_attributes = array(
			'id'            => $model['error_id'],
			'data-ctb-part' => 'error',
			'role'          => 'alert',
			'aria-live'     => 'polite',
			'hidden'        => true,
		);
		return '<div class="ctb-form-field" data-field-type="' . esc_attr( $model['field_type'] ) . '" data-ctb-part="row">'
			. $label_html
			. $control_html
			. '<small' . self::render_attributes( 'small', $help_attributes ) . '>' . esc_html( $model['help'] ) . '</small>'
			. '<span' . self::render_attributes( 'span', $error_attributes ) . '></span>'
			. '</div>';
	}

	/**
	 * Resolve the stable content target for registry-backed text renderers.
	 *
	 * @param array $block Sanitized block.
	 * @return array|null
	 */
	private static function text_render_model( $block ) {
		$element_id = isset( $block['element'] ) && is_string( $block['element'] ) ? $block['element'] : '';
		$definition = '' !== $element_id ? Code_To_Block_Registry::get( $element_id ) : null;
		if (
			null === $definition ||
			'text' !== ( isset( $definition['rendererFamily'] ) ? $definition['rendererFamily'] : '' ) ||
			empty( $definition['targets'] ) ||
			! in_array( 'text', $definition['targets'], true )
		) {
			return null;
		}

		$attributes = isset( $block['attributes'] ) ? self::object_to_array( $block['attributes'] ) : array();
		$href       = isset( $attributes['data-link-url'] ) && is_string( $attributes['data-link-url'] )
			? trim( $attributes['data-link-url'] )
			: '';
		if ( preg_match( '/^(?:javascript|data|vbscript):/i', $href ) ) {
			$href = '';
		}

		return array( 'href' => $href );
	}

	/**
	 * Resolve registry-backed Image props without coupling the generic renderer
	 * to a concrete element ID.
	 *
	 * @param array $block Sanitized block.
	 * @return array|null
	 */
	private static function image_render_model( $block ) {
		$element_id = isset( $block['element'] ) && is_string( $block['element'] ) ? $block['element'] : '';
		$definition = '' !== $element_id ? Code_To_Block_Registry::get( $element_id ) : null;
		if (
			null === $definition ||
			'image' !== ( isset( $definition['rendererFamily'] ) ? $definition['rendererFamily'] : '' ) ||
			empty( $definition['targets'] ) ||
			! in_array( 'media', $definition['targets'], true )
		) {
			return null;
		}

		$props   = isset( $block['props'] ) ? self::object_to_array( $block['props'] ) : array();
		$caption = isset( $props['caption'] ) && is_string( $props['caption'] ) ? trim( $props['caption'] ) : '';
		$link    = isset( $props['link'] ) && is_string( $props['link'] ) ? trim( $props['link'] ) : '';
		if ( preg_match( '/^(?:javascript|data|vbscript):/i', $link ) ) {
			$link = '';
		}
		return array(
			'caption'    => $caption,
			'decorative' => self::attribute_is_true( isset( $props['decorative'] ) ? $props['decorative'] : false ),
			'link'       => $link,
		);
	}

	/**
	 * Render the stable Image root/media/caption target contract.
	 *
	 * @param array $source_attributes Sanitized block attributes.
	 * @param array $model             Resolved Image props.
	 * @return string
	 */
	private static function render_image_element( $source_attributes, $model ) {
		$root_attributes  = $source_attributes;
		$media_attributes = array();
		$media_names      = array( 'alt', 'crossorigin', 'decoding', 'height', 'ismap', 'loading', 'referrerpolicy', 'sizes', 'src', 'srcset', 'title', 'usemap', 'width', 'data-ctb-lazy-media' );
		foreach ( $media_names as $name ) {
			if ( array_key_exists( $name, $root_attributes ) ) {
				$media_attributes[ $name ] = $root_attributes[ $name ];
				unset( $root_attributes[ $name ] );
			}
		}
		$media_attributes['alt']           = $model['decorative'] ? '' : ( isset( $media_attributes['alt'] ) ? $media_attributes['alt'] : '' );
		$media_attributes['class']         = trim( ( isset( $media_attributes['class'] ) ? $media_attributes['class'] : '' ) . ' ctb-image-media' );
		$media_attributes['data-ctb-part'] = 'media';
		$root_attributes['class']          = trim( ( isset( $root_attributes['class'] ) ? $root_attributes['class'] : '' ) . ' ctb-image-root' );

		$children = '<img' . self::render_attributes( 'img', $media_attributes ) . '>';
		if ( '' !== $model['caption'] ) {
			$children .= '<figcaption data-ctb-part="caption">' . esc_html( $model['caption'] ) . '</figcaption>';
		}
		$figure = '<figure' . self::render_attributes( 'figure', $root_attributes ) . '>' . $children . '</figure>';
		return '' !== $model['link']
			? '<a class="ctb-image-link" href="' . esc_url( $model['link'] ) . '">' . $figure . '</a>'
			: $figure;
	}

	/**
	 * @param mixed $value Attribute value.
	 * @return bool
	 */
	private static function attribute_is_true( $value ) {
		if ( true === $value || 1 === $value ) {
			return true;
		}
		return is_string( $value ) && in_array( strtolower( trim( $value ) ), array( '1', 'true', 'yes', 'on' ), true );
	}

	/**
	 * Applies WordPress-native login and role visibility rules.
	 *
	 * @param array $block Sanitized block.
	 * @return bool
	 */
	private static function block_is_visible( $block ) {
		$conditions = isset( $block['visibility_conditions'] ) ? self::object_to_array( $block['visibility_conditions'] ) : array();
		if ( empty( $conditions ) ) {
			return true;
		}
		$logged_in = function_exists( 'is_user_logged_in' ) && is_user_logged_in();
		if ( isset( $conditions['login'] ) ) {
			if ( 'logged_in' === $conditions['login'] && ! $logged_in ) {
				return false;
			}
			if ( 'logged_out' === $conditions['login'] && $logged_in ) {
				return false;
			}
		}
		if ( ! empty( $conditions['roles'] ) ) {
			if ( ! $logged_in || ! function_exists( 'wp_get_current_user' ) ) {
				return false;
			}
			$user_roles = (array) wp_get_current_user()->roles;
			if ( empty( array_intersect( $conditions['roles'], $user_roles ) ) ) {
				return false;
			}
		}
		return true;
	}

	/**
	 * @param string $source Dynamic source key.
	 * @param int    $post_id Context post ID.
	 * @return array
	 */
	private static function get_dynamic_data( $source, $post_id ) {
		$data = array( 'html' => '', 'url' => '', 'srcset' => '', 'alt' => '' );
		if ( strpos( $source, 'wc_product_' ) === 0 && function_exists( 'wc_get_product' ) ) {
			if ( ! in_array( get_post_type( $post_id ), array( 'product', 'product_variation' ), true ) ) {
				return $data;
			}
			$wc_product = wc_get_product( $post_id );
			if ( ! $wc_product ) {
				return $data;
			}
			switch ( $source ) {
				case 'wc_product_title':
					$data['html'] = esc_html( $wc_product->get_name() );
					break;
				case 'wc_product_price':
					$data['html'] = wp_kses_post( $wc_product->get_price_html() );
					break;
				case 'wc_product_short_description':
					$data['html'] = wp_kses_post( apply_filters( 'woocommerce_short_description', $wc_product->get_short_description() ) );
					break;
				case 'wc_product_stock_status':
					$data['html'] = wp_kses_post( wc_get_stock_html( $wc_product ) );
					if ( '' === trim( wp_strip_all_tags( $data['html'] ) ) ) {
						$data['html'] = esc_html( $wc_product->is_in_stock() ? 'In stock' : 'Out of stock' );
					}
					break;
				case 'wc_product_image':
					$image_id = $wc_product->get_image_id();
					if ( $image_id ) {
						$data['url'] = wp_get_attachment_image_url( $image_id, 'full' );
						$data['srcset'] = wp_get_attachment_image_srcset( $image_id, 'full' );
						$data['alt'] = get_post_meta( $image_id, '_wp_attachment_image_alt', true );
						if ( '' === $data['alt'] ) {
							$data['alt'] = wp_strip_all_tags( $wc_product->get_name() );
						}
					}
					break;
				default:
					if ( strpos( $source, 'wc_custom_field_' ) === 0 ) {
						$key = substr( $source, strlen( 'wc_custom_field_' ) );
						$data['html'] = esc_html( $wc_product->get_meta( $key ) );
					}
					break;
			}
		}
		return $data;
	}

	public static function get_woocommerce_block_markup( $name ) {
		$path = dirname( __DIR__ ) . '/templates/woocommerce-' . $name . '-block.html';
		if ( ! is_readable( $path ) ) {
			return '';
		}
		$markup = file_get_contents( $path );
		if ( ! is_string( $markup ) ) {
			return '';
		}
		// Render Interactivity API blocks
		return function_exists( 'do_blocks' ) ? do_blocks( $markup ) : $markup;
	}

	private static function count_rendered_blocks( $children ) {
		$count = 0;
		foreach ( $children as $child ) {
			$child = self::object_to_array( $child );
			if ( isset( $child['kind'] ) ) {
				continue;
			}
			++$count;
			$count += self::count_rendered_blocks( isset( $child['children'] ) ? $child['children'] : array() );
		}
		return $count;
	}

	/**
	 * @param array $block Sanitized block.
	 * @return array
	 */
	private static function runtime_actions_for_block( $block ) {
		$runtime_actions = array();
		foreach ( isset( $block['actions'] ) ? $block['actions'] : array() as $action ) {
			$normalized = Code_To_Block_Schema::normalize_runtime_action( $action );
			if ( null !== $normalized ) {
				$runtime_actions[] = $normalized;
			}
		}
		return $runtime_actions;
	}

	private static function animation_actions_for_block( $block ) {
		$animations = array();
		foreach ( isset( $block['actions'] ) ? $block['actions'] : array() as $action ) {
			$normalized = Code_To_Block_Schema::normalize_animation_action( $action );
			if ( null !== $normalized ) {
				$animations[] = $normalized;
			}
		}
		return $animations;
	}

	private static function css_animation_actions_for_block( $block ) {
		$animations = array();
		foreach ( isset( $block['actions'] ) ? $block['actions'] : array() as $action ) {
			$normalized = Code_To_Block_Schema::normalize_css_animation_action( $action );
			if ( null !== $normalized ) {
				$animations[] = $normalized;
			}
		}
		return $animations;
	}

	/**
	 * @param string $tag        HTML tag.
	 * @param array  $attributes Attribute map.
	 * @return string
	 */
	private static function stable_element_class( $block_id ) {
		return 'ctb-e-' . hash( 'fnv1a32', (string) $block_id );
	}

	private static function render_attributes( $tag, $attributes ) {
		$rendered = '';

		if ( isset( $attributes['target'] ) && is_string( $attributes['target'] ) && '_blank' === strtolower( trim( $attributes['target'] ) ) ) {
			$attributes['target'] = '_blank';
			$rel_tokens = isset( $attributes['rel'] ) && is_string( $attributes['rel'] )
				? preg_split( '/\s+/', trim( $attributes['rel'] ) )
				: array();
			$rel_tokens = array_map( 'strtolower', $rel_tokens );
			$attributes['rel'] = implode( ' ', array_unique( array_filter( array_merge( array( 'noopener', 'noreferrer' ), $rel_tokens ) ) ) );
		}

		foreach ( $attributes as $name => $value ) {
			$name = strtolower( $name );
			if ( ! Code_To_Block_Schema::attribute_is_allowed( $tag, $name ) || false === $value ) {
				continue;
			}
			if ( true === $value ) {
				$rendered .= ' ' . esc_attr( $name );
				continue;
			}
			if ( ! is_string( $value ) ) {
				continue;
			}

			if ( in_array( $name, array( 'href', 'src', 'cite' ), true ) ) {
				$value = esc_url( self::normalize_resource_url( $value ) );
				if ( '' === $value ) {
					continue;
				}
				$rendered .= ' ' . esc_attr( $name ) . '="' . $value . '"';
				continue;
			}
			$rendered .= ' ' . esc_attr( $name ) . '="' . esc_attr( $value ) . '"';
		}

		return $rendered;
	}

	/**
	 * @param mixed $declarations Sanitized v3 declaration object.
	 * @return string
	 */
	private static function v3_declarations( $declarations ) {
		$declarations = self::object_to_array( $declarations );
		if ( ! is_array( $declarations ) ) {
			return '';
		}
		ksort( $declarations, SORT_STRING );
		$result = '';
		foreach ( $declarations as $property => $value ) {
			if ( ! is_string( $property ) || ! is_string( $value ) || ! Code_To_Block_Schema::css_property_value_is_safe( $property, $value ) ) {
				continue;
			}
			$value   = preg_replace( '/\s*!important\s*$/i', '', trim( $value ) );
			$result .= $property . ':' . self::normalize_css_urls( $value ) . ';';
		}
		return $result;
	}

	/**
	 * @param string $context_key Context key.
	 * @return array|null
	 */
	private static function parse_v3_context( $context_key ) {
		if ( 'base' === $context_key ) {
			return array( 'breakpoint' => 'desktop', 'state' => 'default' );
		}
		if ( ! preg_match( '/^(?:bp:(tablet|mobile)(?:\|state:([A-Za-z][A-Za-z0-9]*))?|state:([A-Za-z][A-Za-z0-9]*))$/', $context_key, $matches ) ) {
			return null;
		}
		return array(
			'breakpoint' => ! empty( $matches[1] ) ? $matches[1] : 'desktop',
			'state'      => ! empty( $matches[2] ) ? $matches[2] : ( ! empty( $matches[3] ) ? $matches[3] : 'default' ),
		);
	}

	/**
	 * @param string $selector Root or target selector.
	 * @param string $state State identifier.
	 * @return string
	 */
	private static function v3_state_selector( $selector, $state, $root = '' ) {
		$states = array(
			'hover'        => array( ':hover' ),
			'focusVisible' => array( ':focus-visible' ),
			'focus'        => array( ':focus' ),
			'active'       => array( ':active' ),
			'visited'      => array( ':visited' ),
			'disabled'     => array( ':disabled', '[aria-disabled="true"]' ),
			'checked'      => array( ':checked', '[aria-checked="true"]' ),
			'expanded'     => array( '[aria-expanded="true"]', '[open]' ),
			'selected'     => array( '[aria-selected="true"]' ),
			'invalid'      => array( ':invalid', '[aria-invalid="true"]' ),
			'readOnly'     => array( ':read-only', '[aria-readonly="true"]' ),
			'loading'      => array( '[aria-busy="true"]', '[data-ctb-loading="true"]' ),
			'current'      => array( '[aria-current="page"]', '[aria-current="true"]' ),
			'expired'      => array( '[data-ctb-expired="true"]' ),
		);
		if ( ! isset( $states[ $state ] ) ) {
			return $selector;
		}
		$selectors = array();
		foreach ( $states[ $state ] as $suffix ) {
			if ( '' !== $root && $selector !== $root && 0 === strpos( $selector, $root ) ) {
				$selectors[] = $root . $suffix . substr( $selector, strlen( $root ) );
			}
			if ( preg_match( '/(::[a-z-]+(?:\([^)]*\))?)$/i', $selector, $pseudo_match, PREG_OFFSET_CAPTURE ) ) {
				$pseudo = $pseudo_match[0][0];
				$offset = $pseudo_match[0][1];
				$selectors[] = substr( $selector, 0, $offset ) . $suffix . $pseudo;
			} else {
				$selectors[] = $selector . $suffix;
			}
		}
		return implode( ',', array_unique( $selectors ) );
	}

	/**
	 * @param array  $block Sanitized v3 block.
	 * @param int    $post_id Page ID.
	 * @param array  $rules CSS rule buckets.
	 */
	private static function collect_v3_css_rules( $block, $post_id, &$rules ) {
		$element_id = $block['element'];
		$root       = ':where(#ctb-page-' . (int) $post_id . ') .' . self::stable_element_class( $block['id'] );
		$targets    = self::object_to_array( $block['style']['targets'] );
		ksort( $targets, SORT_STRING );
		foreach ( $targets as $target_id => $target_value ) {
			$target_selector = Code_To_Block_Registry::target_selector( $element_id, $target_id );
			if ( '' === $target_selector ) {
				continue;
			}
			$selector = '&' === $target_selector ? $root : $root . ' > ' . $target_selector;
			$target_value = self::object_to_array( $target_value );
			$contexts = isset( $target_value['contexts'] ) ? self::object_to_array( $target_value['contexts'] ) : array();
			uksort(
				$contexts,
				function ( $left, $right ) {
					$order = array( 'base' => 0, 'bp:tablet' => 10, 'bp:mobile' => 20 );
					$left_weight  = isset( $order[ $left ] ) ? $order[ $left ] : ( false !== strpos( $left, 'state:' ) ? 100 : 999 );
					$right_weight = isset( $order[ $right ] ) ? $order[ $right ] : ( false !== strpos( $right, 'state:' ) ? 100 : 999 );
					return $left_weight === $right_weight ? strcmp( $left, $right ) : $left_weight - $right_weight;
				}
			);
			foreach ( $contexts as $context_key => $style_set ) {
				$context = self::parse_v3_context( $context_key );
				if ( null === $context ) {
					continue;
				}
				$style_set    = self::object_to_array( $style_set );
				$declarations = self::v3_declarations( isset( $style_set['declarations'] ) ? $style_set['declarations'] : array() );
				$custom       = isset( $style_set['custom_declarations'] ) && is_string( $style_set['custom_declarations'] ) ? trim( $style_set['custom_declarations'] ) : '';
				if ( '' !== $custom && Code_To_Block_Schema::css_declaration_list_is_safe( $custom ) ) {
					$declarations .= rtrim( $custom, ';' ) . ';';
				}
				if ( '' !== $declarations ) {
					$bucket = 'desktop' === $context['breakpoint'] ? 'base' : 'v3_' . $context['breakpoint'];
					$rules[ $bucket ][] = self::v3_state_selector( $selector, $context['state'], $root ) . '{' . $declarations . '}';
				}
			}
		}
		$visibility = isset( $block['advanced']['visibility'] ) ? self::object_to_array( $block['advanced']['visibility'] ) : array();
		foreach ( array( 'desktop', 'tablet', 'mobile' ) as $breakpoint ) {
			if ( array_key_exists( $breakpoint, $visibility ) && false === $visibility[ $breakpoint ] ) {
				$bucket = 'desktop' === $breakpoint ? 'base' : 'v3_' . $breakpoint;
				$rules[ $bucket ][] = $root . '{display:none!important;}';
			}
		}
	}

	/**
	 * @param array $block   Sanitized block.
	 * @param int   $post_id Owning post ID.
	 * @param int   $index   Traversal index.
	 * @param array $rules   Collected rules.
	 */
	private static function collect_css_rules( $block, $post_id, &$index, &$rules ) {
		$current_index = $index++;
		if ( ! empty( $block['element'] ) && ! empty( $block['style']['targets'] ) ) {
			self::collect_v3_css_rules( $block, $post_id, $rules );
			foreach ( isset( $block['children'] ) ? $block['children'] : array() as $child ) {
				$child = self::object_to_array( $child );
				if ( ! isset( $child['kind'] ) ) {
					self::collect_css_rules( $child, $post_id, $index, $rules );
				}
			}
			return;
		}
		$selector       = '#ctb-page-' . $post_id . ' .ctb-block-' . $current_index;
		$style_selector = isset( $block['element'] ) && 'core/image' === $block['element']
			? $selector . ' > [data-ctb-part="media"]'
			: $selector;
		self::append_rule( $rules['base'], $style_selector, $block['styles'] );
		$css_animations = self::css_animation_actions_for_block( $block );
		if ( ! empty( $css_animations ) && $css_animations[0]['params']['target_block_id'] === $block['id'] ) {
			$params = $css_animations[0]['params'];
			$rules['base'][] = sprintf(
				'%1$s{--ctb-reveal-y:%2$spx;--ctb-reveal-duration:%3$ss;--ctb-reveal-delay:%4$ss;}',
				$selector,
				(float) $params['from_y'],
				(float) $params['duration'],
				(float) $params['delay']
			);
		}

		$states = isset( $block['states'] ) ? self::object_to_array( $block['states'] ) : array();
		foreach ( array( 'hover', 'focus', 'active' ) as $state ) {
			if ( isset( $states[ $state ] ) ) {
				self::append_rule( $rules['base'], $style_selector . ':' . $state, $states[ $state ] );
			}
		}

		$responsive = isset( $block['responsive_overrides'] ) ? self::object_to_array( $block['responsive_overrides'] ) : array();
		foreach ( array( 'tablet', 'mobile' ) as $viewport ) {
			if ( isset( $responsive[ $viewport ] ) ) {
				self::append_rule( $rules[ $viewport ], $style_selector, $responsive[ $viewport ] );
			}
		}

		$is_saved_component = isset( $block['meta']['saved_component_id'] );
		try {
			foreach ( $block['children'] as $child ) {
				$child = self::object_to_array( $child );
				if ( ! isset( $child['kind'] ) ) {
					self::collect_css_rules( $child, $post_id, $index, $rules );
				}
			}
		} catch ( Throwable $error ) {
			if ( ! $is_saved_component ) {
				throw $error;
			}
		}
	}

	/**
	 * @param array $block    Sanitized block.
	 * @param array $snapshot Collected declarations keyed by block ID and context.
	 */
	private static function collect_style_snapshot( $block, &$snapshot ) {
		$block_id = isset( $block['id'] ) ? $block['id'] : '';
		$styles   = array( 'base' => isset( $block['styles'] ) ? $block['styles'] : null );

		$states = isset( $block['states'] ) ? self::object_to_array( $block['states'] ) : array();
		foreach ( array( 'hover', 'focus', 'active' ) as $state ) {
			if ( isset( $states[ $state ] ) ) {
				$styles[ $state ] = $states[ $state ];
			}
		}

		$responsive = isset( $block['responsive_overrides'] ) ? self::object_to_array( $block['responsive_overrides'] ) : array();
		foreach ( array( 'tablet', 'mobile' ) as $viewport ) {
			if ( isset( $responsive[ $viewport ] ) ) {
				$styles[ $viewport ] = $responsive[ $viewport ];
			}
		}

		foreach ( $styles as $context => $style ) {
			$declarations = self::style_declarations( $style );
			if ( '' !== $block_id && '' !== $declarations ) {
				$snapshot[ $block_id ][ $context ] = $declarations;
			}
		}

		foreach ( isset( $block['children'] ) ? $block['children'] : array() as $child ) {
			$child = self::object_to_array( $child );
			if ( ! isset( $child['kind'] ) ) {
				self::collect_style_snapshot( $child, $snapshot );
			}
		}
	}

	/**
	 * @param array  $rules    Destination list.
	 * @param string $selector Scoped selector.
	 * @param mixed  $style    Style set.
	 */
	private static function append_rule( &$rules, $selector, $style ) {
		$declarations = self::style_declarations( $style );
		if ( '' !== $declarations ) {
			$rules[] = $selector . '{' . $declarations . '}';
		}
	}

	/**
	 * @param mixed $style Style set.
	 * @return string
	 */
	private static function style_declarations( $style ) {
		$style = self::object_to_array( $style );
		if ( ! is_array( $style ) ) {
			return '';
		}

		$mapped      = isset( $style['mapped'] ) ? self::object_to_array( $style['mapped'] ) : array();
		$declarations = '';
		foreach ( $mapped as $property => $value ) {
			if ( ! is_string( $value ) || ! Code_To_Block_Schema::css_property_value_is_safe( $property, $value ) ) {
				continue;
			}
			$value         = preg_replace( '/\s*!important\s*$/i', '', trim( $value ) );
			$value         = self::normalize_css_urls( $value );
			$declarations .= $property . ':' . $value . '!important;';
		}

		$fallback = isset( $style['custom_css_fallback'] ) ? trim( $style['custom_css_fallback'] ) : '';
		if ( '' !== $fallback && Code_To_Block_Schema::css_declaration_list_is_safe( $fallback ) ) {
			$declarations .= rtrim( $fallback, ';' ) . ';';
		}

		return $declarations;
	}

	/**
	 * @param mixed $design_tokens Sanitized document token registry.
	 * @return string
	 */
	private static function design_token_declarations( $design_tokens ) {
		$design_tokens = self::object_to_array( $design_tokens );
		$declarations  = '';
		foreach ( Code_To_Block_Schema::TOKEN_CATEGORIES as $category ) {
			$tokens = isset( $design_tokens[ $category ] ) ? self::object_to_array( $design_tokens[ $category ] ) : array();
			foreach ( $tokens as $id => $token ) {
				$token = self::object_to_array( $token );
				$name  = Code_To_Block_Schema::design_token_css_name( $category . '.' . $id );
				$value = isset( $token['value'] ) && is_string( $token['value'] ) ? $token['value'] : '';
				if ( '' === $name || '' === $value || ! Code_To_Block_Schema::css_property_value_is_safe( $name, $value ) ) {
					continue;
				}
				$declarations .= $name . ':' . self::normalize_css_urls( trim( $value ) ) . ';';
			}
		}
		return $declarations;
	}

	/**
	 * Returns imported styles after the parser has scoped every selector to the
	 * imported page root. Original unscoped source is never emitted.
	 */
	private static function imported_stylesheet_css( $document ) {
		$assets = isset( $document['imported_assets'] ) ? self::object_to_array( $document['imported_assets'] ) : array();
		$stylesheets = isset( $assets['stylesheets'] ) && is_array( $assets['stylesheets'] ) ? $assets['stylesheets'] : array();
		$css = '';
		foreach ( $stylesheets as $stylesheet_value ) {
			$stylesheet = self::object_to_array( $stylesheet_value );
			$source = isset( $stylesheet['scoped_source'] ) && is_string( $stylesheet['scoped_source'] ) ? $stylesheet['scoped_source'] : '';
			if ( '' === $source || preg_match( '/(?:expression\s*\(|javascript\s*:|<\s*\/\s*style)/i', $source ) ) {
				continue;
			}
			$css .= "\n/* Imported stylesheet */\n" . self::normalize_stylesheet_urls( $source ) . "\n";
		}
		return $css;
	}

	private static function imported_token_declarations( $document ) {
		$assets = isset( $document['imported_assets'] ) ? self::object_to_array( $document['imported_assets'] ) : array();
		$bindings = isset( $assets['token_bindings'] ) ? self::object_to_array( $assets['token_bindings'] ) : array();
		$tokens = isset( $document['design_tokens'] ) ? self::object_to_array( $document['design_tokens'] ) : array();
		$declarations = '';
		foreach ( $bindings as $css_name => $reference ) {
			if ( ! is_string( $css_name ) || ! preg_match( '/^--[a-z0-9_-]+$/i', $css_name ) || ! is_string( $reference ) ) {
				continue;
			}
			$parts = explode( '.', $reference, 2 );
			if ( 2 !== count( $parts ) ) continue;
			$category_tokens = isset( $tokens[ $parts[0] ] ) ? self::object_to_array( $tokens[ $parts[0] ] ) : array();
			$token = isset( $category_tokens[ $parts[1] ] ) ? self::object_to_array( $category_tokens[ $parts[1] ] ) : array();
			$value = isset( $token['value'] ) && is_string( $token['value'] ) ? $token['value'] : '';
			if ( '' !== $value && Code_To_Block_Schema::css_property_value_is_safe( $css_name, $value ) ) {
				$declarations .= $css_name . ':' . self::normalize_css_urls( $value ) . ';';
			}
		}
		return $declarations;
	}

	private static function normalize_stylesheet_urls( $css ) {
		return preg_replace_callback(
			'/url\(\s*(["\']?)([^"\')]+)\1\s*\)/i',
			function ( $matches ) {
				return 'url(' . $matches[1] . self::normalize_resource_url( $matches[2] ) . $matches[1] . ')';
			},
			$css
		);
	}

	/**
	 * Produces imported page scripts for the isolated frontend Preview/Publish
	 * document. This method is never called by the visual editor canvas.
	 */
	public static function render_imported_scripts( $document, $preview, $placement ) {
		$assets = isset( $document['imported_assets'] ) ? self::object_to_array( $document['imported_assets'] ) : array();
		$scripts = isset( $assets['scripts'] ) && is_array( $assets['scripts'] ) ? $assets['scripts'] : array();
		$html = '';
		foreach ( $scripts as $script_value ) {
			$script = self::object_to_array( $script_value );
			$script_placement = isset( $script['placement'] ) ? $script['placement'] : 'body-end';
			if ( $script_placement !== $placement ) continue;
			$enabled = $preview ? ! empty( $script['enabled_in_preview'] ) : ! empty( $script['enabled_on_publish'] );
			if ( ! $enabled ) continue;
			$type = isset( $script['type'] ) && is_string( $script['type'] ) ? $script['type'] : 'text/javascript';
			$attributes = ' type="' . esc_attr( $type ) . '" data-ctb-imported-script="1"';
			$source_attributes = isset( $script['attributes'] ) ? self::object_to_array( $script['attributes'] ) : array();
			foreach ( array( 'async', 'defer', 'nomodule' ) as $boolean_attribute ) {
				if ( array_key_exists( $boolean_attribute, $source_attributes ) ) {
					$attributes .= ' ' . $boolean_attribute;
				}
			}
			if ( isset( $source_attributes['id'] ) && is_string( $source_attributes['id'] ) && preg_match( '/^[A-Za-z][A-Za-z0-9:._-]{0,99}$/', $source_attributes['id'] ) ) {
				$attributes .= ' id="' . esc_attr( $source_attributes['id'] ) . '"';
			}
			if ( isset( $source_attributes['crossorigin'] ) && in_array( $source_attributes['crossorigin'], array( 'anonymous', 'use-credentials' ), true ) ) {
				$attributes .= ' crossorigin="' . esc_attr( $source_attributes['crossorigin'] ) . '"';
			}
			if ( isset( $source_attributes['referrerpolicy'] ) && in_array( $source_attributes['referrerpolicy'], array( 'no-referrer', 'no-referrer-when-downgrade', 'origin', 'origin-when-cross-origin', 'same-origin', 'strict-origin', 'strict-origin-when-cross-origin', 'unsafe-url' ), true ) ) {
				$attributes .= ' referrerpolicy="' . esc_attr( $source_attributes['referrerpolicy'] ) . '"';
			}
			if ( isset( $source_attributes['integrity'] ) && is_string( $source_attributes['integrity'] ) && preg_match( '/^sha(?:256|384|512)-[A-Za-z0-9+\/=]+(?:\s+sha(?:256|384|512)-[A-Za-z0-9+\/=]+)*$/', $source_attributes['integrity'] ) ) {
				$attributes .= ' integrity="' . esc_attr( $source_attributes['integrity'] ) . '"';
			}
			foreach ( $source_attributes as $name => $value ) {
				if ( is_string( $name ) && 'data-ctb-imported-script' !== $name && preg_match( '/^data-[a-z0-9_.:-]+$/', $name ) && is_string( $value ) && strlen( $value ) <= 1000 ) {
					$attributes .= ' ' . $name . '="' . esc_attr( $value ) . '"';
				}
			}
			if ( isset( $script['src'] ) && is_string( $script['src'] ) ) {
				$src = esc_url( self::normalize_resource_url( $script['src'], self::imported_resource_base( $document ) ) );
				if ( '' !== $src ) $html .= '<script' . $attributes . ' src="' . $src . '"></script>' . "\n";
				continue;
			}
			$source = isset( $script['source'] ) && is_string( $script['source'] ) ? $script['source'] : '';
			if ( '' !== $source && ! preg_match( '/<\s*\/\s*script/i', $source ) ) {
				$html .= '<script' . $attributes . '>' . $source . '</script>' . "\n";
			}
		}
		return $html;
	}

	/**
	 * Resolves relative imported resources consistently in admin and frontend.
	 *
	 * @param string      $url           Resource URL.
	 * @param string|null $resource_base Optional imported document base URL.
	 * @return string
	 */
	private static function normalize_resource_url( $url, $resource_base = null ) {
		$url = trim( $url );
		if ( '' === $url || preg_match( '#^(?:[a-z][a-z0-9+.-]*:|//|/|\#)#i', $url ) ) {
			return $url;
		}

		$base = null === $resource_base ? self::$resource_base : $resource_base;
		if ( '' !== $base ) {
			$resolved = self::resolve_relative_resource_url( $url, $base );
			if ( '' !== $resolved ) {
				return $resolved;
			}
		}

		return trailingslashit( home_url() ) . ltrim( $url, '/' );
	}

	/**
	 * Returns a safe base URL recorded from an imported HTML document.
	 *
	 * @param array $document Sanitized document.
	 * @return string
	 */
	private static function imported_resource_base( $document ) {
		$assets    = isset( $document['imported_assets'] ) ? self::object_to_array( $document['imported_assets'] ) : array();
		$page_meta = isset( $assets['page_meta'] ) ? self::object_to_array( $assets['page_meta'] ) : array();
		$base      = isset( $page_meta['base_href'] ) && is_string( $page_meta['base_href'] ) ? trim( $page_meta['base_href'] ) : '';
		if ( '' === $base || preg_match( '#^(?:javascript|data|vbscript):#i', $base ) ) {
			return '';
		}
		if ( preg_match( '#^[a-z][a-z0-9+.-]*:#i', $base ) && ! preg_match( '#^https?://#i', $base ) ) {
			return '';
		}
		return $base;
	}

	/**
	 * Resolves a relative resource using HTML <base href> semantics.
	 *
	 * @param string $url  Relative resource URL.
	 * @param string $base Imported base URL.
	 * @return string
	 */
	private static function resolve_relative_resource_url( $url, $base ) {
		$site       = rtrim( home_url(), '/' );
		$site_parts = parse_url( $site );
		$scheme     = isset( $site_parts['scheme'] ) ? $site_parts['scheme'] : 'https';

		if ( 0 === strpos( $base, '//' ) ) {
			$base = $scheme . ':' . $base;
		} elseif ( 0 === strpos( $base, '/' ) ) {
			$origin = isset( $site_parts['scheme'], $site_parts['host'] ) ? $site_parts['scheme'] . '://' . $site_parts['host'] : $site;
			if ( isset( $site_parts['port'] ) ) {
				$origin .= ':' . $site_parts['port'];
			}
			$base = $origin . $base;
		} elseif ( ! preg_match( '#^https?://#i', $base ) ) {
			$base = trailingslashit( $site ) . ltrim( $base, '/' );
		}

		$base_parts = parse_url( $base );
		$url_parts  = parse_url( $url );
		if ( false === $base_parts || false === $url_parts || empty( $base_parts['scheme'] ) || empty( $base_parts['host'] ) || ! in_array( strtolower( $base_parts['scheme'] ), array( 'http', 'https' ), true ) ) {
			return '';
		}

		$base_path = isset( $base_parts['path'] ) ? $base_parts['path'] : '/';
		$directory = '/' === substr( $base_path, -1 ) ? $base_path : dirname( $base_path ) . '/';
		$url_path  = isset( $url_parts['path'] ) ? $url_parts['path'] : '';
		$segments  = explode( '/', $directory . $url_path );
		$normalized_segments = array();
		foreach ( $segments as $segment ) {
			if ( '' === $segment || '.' === $segment ) {
				continue;
			}
			if ( '..' === $segment ) {
				array_pop( $normalized_segments );
				continue;
			}
			$normalized_segments[] = $segment;
		}

		$resolved = strtolower( $base_parts['scheme'] ) . '://' . $base_parts['host'];
		if ( isset( $base_parts['port'] ) ) {
			$resolved .= ':' . $base_parts['port'];
		}
		$resolved .= '/' . implode( '/', $normalized_segments );
		if ( '' !== $url_path && '/' === substr( $url_path, -1 ) ) {
			$resolved .= '/';
		}
		if ( isset( $url_parts['query'] ) ) {
			$resolved .= '?' . $url_parts['query'];
		}
		if ( isset( $url_parts['fragment'] ) ) {
			$resolved .= '#' . $url_parts['fragment'];
		}
		return $resolved;
	}

	/**
	 * @param string $value CSS declaration value.
	 * @return string
	 */
	private static function normalize_css_urls( $value ) {
		return preg_replace_callback(
			'/url\(\s*(["\']?)([^"\')]+)\1\s*\)/i',
			function ( $matches ) {
				$quote = $matches[1];
				return 'url(' . $quote . self::normalize_resource_url( $matches[2] ) . $quote . ')';
			},
			$value
		);
	}

	/**
	 * @param int         $post_id          Owning post ID.
	 * @param array       $document         Sanitized block document.
	 * @param bool        $create_directory Whether to create the asset directory.
	 * @param string|null $css              Pre-generated stylesheet.
	 * @return array|WP_Error
	 */
	private static function get_asset_location( $post_id, $document, $create_directory, $css = null ) {
		$uploads = wp_upload_dir();
		if ( ! empty( $uploads['error'] ) ) {
			return self::filesystem_error( $uploads['error'] );
		}

		$directory = trailingslashit( $uploads['basedir'] ) . self::ASSET_DIRECTORY;
		if ( $create_directory && ! is_dir( $directory ) ) {
			if ( ! wp_mkdir_p( $directory ) ) {
				return self::filesystem_error( 'The stylesheet directory could not be created.' );
			}
		}
		
		if ( $create_directory ) {
			$htaccess_path = trailingslashit( $directory ) . '.htaccess';
			if ( ! file_exists( $htaccess_path ) ) {
				$htaccess_content = "<IfModule mod_expires.c>\n\tExpiresActive On\n\tExpiresByType text/css \"access plus 1 year\"\n</IfModule>\n<IfModule mod_headers.c>\n\t<FilesMatch \"\.css$\">\n\t\tHeader set Cache-Control \"public, max-age=31536000, immutable\"\n\t</FilesMatch>\n</IfModule>\n";
				@file_put_contents( $htaccess_path, $htaccess_content );
			}
		}

		if ( null === $css ) {
			$css = self::generate_css( $document, $post_id );
		}
		$filename = 'ctb-page-' . (int) $post_id . '-' . substr( hash( 'sha256', $css ), 0, 16 ) . '.css';
		return array(
			'directory' => $directory,
			'path'      => trailingslashit( $directory ) . $filename,
			'url'       => trailingslashit( $uploads['baseurl'] ) . self::ASSET_DIRECTORY . '/' . $filename,
		);
	}

	/**
	 * @param string $message Error detail.
	 * @return WP_Error
	 */
	private static function filesystem_error( $message ) {
		return new WP_Error(
			'code_to_block_css_write_failed',
			$message,
			array( 'status' => 500 )
		);
	}

	/**
	 * @param mixed $value Potential object.
	 * @return mixed
	 */
	private static function object_to_array( $value ) {
		return is_object( $value ) ? get_object_vars( $value ) : $value;
	}
}
