<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Renders saved block documents and manages their generated stylesheets.
 */
final class Code_To_Block_Renderer {
	const ASSET_DIRECTORY = 'code-to-block';

	/**
	 * Produces the public markup for a block document.
	 *
	 * @param array $document Sanitized block document.
	 * @param int   $post_id  Owning post ID.
	 * @return string
	 */
	public static function render_document( $document, $post_id ) {
		if ( ! is_array( $document ) || ! isset( $document['root'] ) ) {
			return '';
		}

		$index = 0;
		Code_To_Block_Shortcodes::register_for_post( (int) $post_id );
		try {
			$markup = sprintf(
				'<div id="ctb-page-%1$d" class="ctb-page" data-ctb-post-id="%1$d">%2$s</div>',
				(int) $post_id,
				self::render_block( $document['root'], $index, (int) $post_id )
			);
		} finally {
			Code_To_Block_Shortcodes::unregister_for_post( (int) $post_id );
		}
		return $markup;
	}

	/**
	 * Produces the complete scoped stylesheet for a block document.
	 *
	 * @param array $document Sanitized block document.
	 * @param int   $post_id  Owning post ID.
	 * @return string
	 */
	public static function generate_css( $document, $post_id ) {
		if ( ! is_array( $document ) || ! isset( $document['root'] ) ) {
			return '';
		}

		$rules = array(
			'base'   => array(),
			'tablet' => array(),
			'mobile' => array(),
		);
		$index = 0;
		self::collect_css_rules( $document['root'], (int) $post_id, $index, $rules );

		$css = sprintf(
			"/* Generated by Code to Block. Do not edit. */\n#ctb-page-%1\$d,#ctb-page-%1\$d *{box-sizing:border-box;}\n#ctb-page-%1\$d>.ctb-block-0{width:100%%;}\n",
			(int) $post_id
		);
		// Protected focus indicator: visible by default for keyboard users, not trivially stripped
		$css .= sprintf( "#ctb-page-%d [data-ctb-actions]:focus-visible,#ctb-page-%d a:focus-visible,#ctb-page-%d button:focus-visible{outline:2px solid #6558d3;outline-offset:2px;}\n", (int) $post_id, (int) $post_id, (int) $post_id );
		$css .= sprintf( "@keyframes ctb-reveal-%1\$d{from{opacity:0;transform:translateY(var(--ctb-reveal-y,30px));}to{opacity:1;transform:none;}}\n#ctb-page-%1\$d [data-ctb-css-animation=\"reveal\"]{animation:ctb-reveal-%1\$d var(--ctb-reveal-duration,.6s) ease-out var(--ctb-reveal-delay,0s) both;}\n@media (prefers-reduced-motion:reduce){#ctb-page-%1\$d [data-ctb-css-animation=\"reveal\"]{animation:none;}}\n", (int) $post_id );
		$css .= sprintf( "@keyframes ctb-shimmer{0%%{background-position:-1000px 0;}100%%{background-position:1000px 0;}}\n#ctb-page-%1\$d .ctb-skeleton{background:#e2e2e2;background-image:linear-gradient(90deg,#e2e2e2 0px,#f0f0f0 100px,#e2e2e2 200px);background-size:1000px 100%%;animation:ctb-shimmer 2s infinite linear;border-radius:4px;opacity:0.6;}\n#ctb-page-%1\$d .ctb-skeleton-bar{height:20px;margin-bottom:8px;}\n#ctb-page-%1\$d .ctb-skeleton-image{height:200px;width:100%%;}\n#ctb-page-%1\$d .ctb-skeleton-link{height:40px;width:120px;border-radius:20px;}\n", (int) $post_id );
		$css .= sprintf( "#ctb-page-%1\$d [data-ctb-lazy-media]{background-color:#e9ebf3;background-image:linear-gradient(90deg,#e9ebf3 0,#f6f7fb 42%%,#e9ebf3 82%%);background-size:220%% 100%%;animation:ctb-shimmer 1.6s linear infinite;transition:opacity .24s ease,background-color .24s ease;}\n#ctb-page-%1\$d [data-ctb-lazy-media].is-loaded,#ctb-page-%1\$d [data-ctb-lazy-media].is-error{background-image:none;animation:none;}\n@media (prefers-reduced-motion:reduce){#ctb-page-%1\$d [data-ctb-lazy-media]{animation:none;transition:none;}}\n", (int) $post_id );
		$token_declarations = self::design_token_declarations( isset( $document['design_tokens'] ) ? $document['design_tokens'] : array() );
		if ( '' !== $token_declarations ) {
			$css .= '#ctb-page-' . (int) $post_id . '{' . $token_declarations . "}\n";
		}
		$css .= implode( "\n", $rules['base'] );
		if ( ! empty( $rules['tablet'] ) ) {
			$css .= "\n@media (max-width:1024px){\n" . implode( "\n", $rules['tablet'] ) . "\n}";
		}
		if ( ! empty( $rules['mobile'] ) ) {
			$css .= "\n@media (max-width:767px){\n" . implode( "\n", $rules['mobile'] ) . "\n}";
		}

		return $css . "\n";
	}

	/**
	 * Collects the declarations emitted by the frontend CSS renderer per block.
	 *
	 * @param array $document Sanitized, resolved block document.
	 * @return array
	 */
	public static function style_snapshot( $document ) {
		if ( ! is_array( $document ) || ! isset( $document['root'] ) ) {
			return array();
		}

		$snapshot = array();
		self::collect_style_snapshot( $document['root'], $snapshot );
		return $snapshot;
	}

	/**
	 * Writes a per-post stylesheet to the uploads directory.
	 *
	 * @param int   $post_id  Owning post ID.
	 * @param array $document Sanitized block document.
	 * @return array|WP_Error Asset path and URL, or an error.
	 */
	public static function write_stylesheet( $post_id, $document ) {
		$css   = self::generate_css( $document, $post_id );
		$asset = self::get_asset_location( $post_id, $document, true, $css );
		if ( is_wp_error( $asset ) ) {
			return $asset;
		}
		if ( file_exists( $asset['path'] ) ) {
			// Protect an asset selected by an in-flight save from grace-period cleanup.
			@touch( $asset['path'] );
			return $asset;
		}

		$temp_path = tempnam( $asset['directory'], 'ctb-' );
		if ( false === $temp_path ) {
			return self::filesystem_error( 'The temporary stylesheet could not be created.' );
		}

		$written = file_put_contents( $temp_path, $css, LOCK_EX );
		if ( false === $written || strlen( $css ) !== $written ) {
			@unlink( $temp_path );
			return self::filesystem_error( 'The generated stylesheet could not be written.' );
		}

		if ( ! @rename( $temp_path, $asset['path'] ) ) {
			// PHP on Windows cannot replace an existing file with rename().
			if ( file_exists( $asset['path'] ) ) {
				@unlink( $asset['path'] );
			}
			if ( ! @rename( $temp_path, $asset['path'] ) ) {
				@unlink( $temp_path );
				return self::filesystem_error( 'The generated stylesheet could not be installed.' );
			}
		}

		return $asset;
	}

	/**
	 * Returns a generated asset when it exists.
	 *
	 * @param int $post_id Owning post ID.
	 * @return array|WP_Error
	 */
	public static function get_stylesheet( $post_id, $document ) {
		return self::get_asset_location( $post_id, $document, false );
	}

	/**
	 * Retires superseded assets, preserving them for cached or in-flight pages.
	 *
	 * @param int    $post_id     Owning post ID.
	 * @param string $current_path Current stylesheet path.
	 */
	public static function retire_stale_stylesheets( $post_id, $current_path ) {
		$uploads = wp_upload_dir();
		if ( ! empty( $uploads['error'] ) ) {
			return;
		}

		$directory = trailingslashit( $uploads['basedir'] ) . self::ASSET_DIRECTORY;
		$paths     = glob( trailingslashit( $directory ) . 'ctb-page-' . (int) $post_id . '-*.css' );
		$cutoff    = time() - DAY_IN_SECONDS;
		foreach ( is_array( $paths ) ? $paths : array() as $path ) {
			$marker = $path . '.obsolete';
			if ( $path === $current_path ) {
				if ( file_exists( $marker ) ) {
					@unlink( $marker );
				}
				continue;
			}
			if ( file_exists( $marker ) && filemtime( $marker ) < $cutoff ) {
				@unlink( $path );
				@unlink( $marker );
			} elseif ( ! file_exists( $marker ) ) {
				@touch( $marker );
			}
		}
	}

	/**
	 * Removes a generated per-post stylesheet.
	 *
	 * @param int $post_id Owning post ID.
	 */
	public static function delete_stylesheet( $post_id ) {
		$uploads = wp_upload_dir();
		if ( ! empty( $uploads['error'] ) ) {
			return;
		}

		$directory = trailingslashit( $uploads['basedir'] ) . self::ASSET_DIRECTORY;
		$paths     = glob( trailingslashit( $directory ) . 'ctb-page-' . (int) $post_id . '-*.css' );
		foreach ( is_array( $paths ) ? $paths : array() as $path ) {
			@unlink( $path );
			if ( file_exists( $path . '.obsolete' ) ) {
				@unlink( $path . '.obsolete' );
			}
		}
		$legacy_path = trailingslashit( $directory ) . 'ctb-page-' . (int) $post_id . '.css';
		if ( file_exists( $legacy_path ) ) {
			@unlink( $legacy_path );
		}
	}

	/**
	 * @param array $block Sanitized block.
	 * @param int   $index   Traversal index.
	 * @param int   $post_id Owning page.
	 * @return string
	 */
	private static function render_block( $block, &$index, $post_id ) {
		if ( ! is_array( $block ) || empty( $block['tag'] ) ) {
			return '';
		}

		$current_index = $index++;
		$tag           = strtolower( $block['tag'] );
		if ( ! in_array( $tag, Code_To_Block_Schema::HTML_TAGS, true ) ) {
			return '';
		}
		if ( ! self::block_is_visible( $block ) ) {
			$index += self::count_rendered_blocks( isset( $block['children'] ) ? $block['children'] : array() );
			return '';
		}

		$attributes          = self::object_to_array( $block['attributes'] );
		$attributes          = is_array( $attributes ) ? $attributes : array();
		$attributes['data-ctb-block-id'] = $block['id'];
		$runtime_actions = self::runtime_actions_for_block( $block );
		if ( ! empty( $runtime_actions ) ) {
			$encoded_actions = wp_json_encode( $runtime_actions, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE );
			if ( false !== $encoded_actions ) {
				$attributes['data-ctb-actions'] = $encoded_actions;
			}
			// Keyboard operability: ensure trigger is focusable and has ARIA
			if ( ! isset( $attributes['tabindex'] ) ) {
				// Buttons/links are natively focusable; divs/spans need tabindex
				if ( ! in_array( $tag, array( 'button', 'a', 'input', 'select', 'textarea' ), true ) ) {
					$attributes['tabindex'] = '0';
					if ( ! isset( $attributes['role'] ) ) {
						$attributes['role'] = 'button';
					}
				}
			}
			// For toggle-visibility, set aria-expanded false initially; aria-haspopup hints dropdown
			$has_toggle = false;
			foreach ( $runtime_actions as $ra ) {
				if ( 'toggle-visibility' === $ra['behavior'] || 'show' === $ra['behavior'] || 'hide' === $ra['behavior'] ) {
					$has_toggle = true;
					break;
				}
			}
			if ( $has_toggle ) {
				if ( ! isset( $attributes['aria-expanded'] ) ) {
					$attributes['aria-expanded'] = 'false';
				}
				if ( ! isset( $attributes['aria-haspopup'] ) ) {
					$attributes['aria-haspopup'] = 'true';
				}
			}
		}
		$animation_actions = self::animation_actions_for_block( $block );
		if ( ! empty( $animation_actions ) ) {
			$encoded_animations = wp_json_encode( $animation_actions, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE );
			if ( false !== $encoded_animations ) {
				$attributes['data-ctb-animations'] = $encoded_animations;
			}
		}
		$css_animations = self::css_animation_actions_for_block( $block );
		if ( ! empty( $css_animations ) ) {
			$params = $css_animations[0]['params'];
			if ( $params['target_block_id'] === $block['id'] ) {
				$attributes['data-ctb-css-animation'] = 'reveal';
			}
		}
		// Icon handling: decorative images with empty alt should be hidden from screen readers already via alt=""; ensure presentation role not needed.
		// Functional icon-only buttons (button tag with no text, only image) should have aria-label via checker, not auto-guessed here.
		$existing_class      = isset( $attributes['class'] ) && is_string( $attributes['class'] ) ? $attributes['class'] : '';
		$existing_class      = preg_replace( '/(?:^|\s)ctb-block(?:-\d+)?(?=\s|$)/', '', $existing_class );
		$attributes['class'] = trim( $existing_class . ' ctb-block ctb-block-' . $current_index );
		$children = '';
		$is_saved_component = isset( $block['meta']['saved_component_id'] );
		$is_dynamic = ! empty( $block['is_dynamic'] ) && ! empty( $block['dynamic_source'] );
		
		if ( $is_dynamic ) {
			$dynamic_data = self::get_dynamic_data( $block['dynamic_source'], $post_id );
			if ( 'img' === $tag ) {
				if ( ! empty( $dynamic_data['url'] ) ) {
					$attributes['src'] = $dynamic_data['url'];
				}
				if ( isset( $dynamic_data['srcset'] ) ) {
					$attributes['srcset'] = $dynamic_data['srcset'];
				}
				if ( isset( $dynamic_data['alt'] ) ) {
					$attributes['alt'] = $dynamic_data['alt'];
				}
			}
		}
		$performance = isset( $block['performance'] ) ? self::object_to_array( $block['performance'] ) : array();
		$lazy_media =
			( ! empty( $performance['lazy_load'] ) && in_array( $tag, array( 'img', 'iframe' ), true ) ) ||
			( 'img' === $tag && ! empty( $performance['image_lazy_load'] ) );
		if ( $lazy_media ) {
			$attributes['loading'] = 'lazy';
			$attributes['data-ctb-lazy-media'] = 'true';
			$attributes['class'] = trim( ( isset( $attributes['class'] ) ? $attributes['class'] : '' ) . ' ctb-lazy-media' );
			if ( 'img' === $tag ) {
				$attributes['decoding'] = 'async';
			}
		}
		
		$attribute_html = self::render_attributes( $tag, $attributes );

		if ( in_array( $tag, Code_To_Block_Schema::VOID_TAGS, true ) ) {
			return '<' . $tag . $attribute_html . '>';
		}

		try {
			if ( 'woocommerce_cart' === $block['type'] ) {
				$children = self::get_woocommerce_block_markup( 'cart' );
			} elseif ( 'woocommerce_checkout' === $block['type'] ) {
				$children = self::get_woocommerce_block_markup( 'checkout' );
			} elseif ( 'woocommerce_product' === $block['type'] ) {
				$product_id = isset( $attributes['data-product-id'] ) ? (int) $attributes['data-product-id'] : 0;
				if ( ! $product_id && in_array( get_post_type( $post_id ), array( 'product', 'product_variation' ), true ) ) {
					$product_id = $post_id;
				}
				$wc_product = $product_id && function_exists( 'wc_get_product' ) ? wc_get_product( $product_id ) : false;
				if ( ! $wc_product ) {
					$children = '<p class="ctb-product-empty">Select a valid WooCommerce product.</p>';
				} else {
					foreach ( $block['children'] as $child ) {
						$child = self::object_to_array( $child );
						if ( isset( $child['kind'] ) && 'text' === $child['kind'] ) {
							$children .= Code_To_Block_Shortcodes::render_text( $child['value'], $product_id );
						} else {
							$children .= self::render_block( $child, $index, $product_id );
						}
					}
					if ( 'true' === ( isset( $attributes['data-show-variations'] ) ? $attributes['data-show-variations'] : '' ) ) {
						$children .= Code_To_Block_Commerce::variation_selector( $wc_product );
					}
				}
			} elseif ( 'woocommerce_product_grid' === $block['type'] ) {
				// Grid loops products; children is template for one item. Render grid wrapper + repeated items.
				$template_start_index = $index;
				$template_block_count = self::count_rendered_blocks( $block['children'] );
				$grid_limit = isset( $attributes['data-grid-limit'] ) ? max( 1, min( 12, (int) $attributes['data-grid-limit'] ) ) : 6;
				$grid_products = array();
				if ( function_exists( 'wc_get_products' ) ) {
					$query_args = array( 'limit' => $grid_limit, 'status' => 'publish', 'orderby' => 'date', 'order' => 'DESC' );
					if ( isset( $attributes['data-product-category'] ) && '' !== trim( $attributes['data-product-category'] ) ) {
						$query_args['category'] = array( sanitize_text_field( $attributes['data-product-category'] ) );
					}
					$grid_products = wc_get_products( $query_args );
				}
				if ( empty( $grid_products ) ) {
					$children = '<p class="ctb-product-grid-empty">No products found.</p>';
				} else {
					$grid_items = '';
					foreach ( $grid_products as $grid_product ) {
						$item_index = $template_start_index;
						$grid_product_id = $grid_product->get_id();
						$item_inner = '';
						if ( empty( $block['children'] ) ) {
							$img_data = self::get_dynamic_data( 'wc_product_image', $grid_product_id );
							$title_data = self::get_dynamic_data( 'wc_product_title', $grid_product_id );
							$price_data = self::get_dynamic_data( 'wc_product_price', $grid_product_id );
							$img_html = ! empty( $img_data['url'] ) ? '<img src="' . esc_url( $img_data['url'] ) . '" alt="' . esc_attr( $img_data['alt'] ) . '" style="width:100%;height:auto;">' : '';
							$grid_items .= '<li class="product type-product status-publish ctb-product-grid-item" data-product-id="' . (int) $grid_product_id . '">' . $img_html . '<h3>' . $title_data['html'] . '</h3><div>' . $price_data['html'] . '</div></li>';
						} else {
							foreach ( $block['children'] as $child ) {
								$child = self::object_to_array( $child );
								if ( isset( $child['kind'] ) && 'text' === $child['kind'] ) {
									$item_inner .= Code_To_Block_Shortcodes::render_text( $child['value'], $grid_product_id );
								} else {
								$item_inner .= self::render_block( $child, $item_index, $grid_product_id );
								}
							}
							$grid_items .= '<li class="product type-product status-publish ctb-product-grid-item" data-product-id="' . (int) $grid_product_id . '">' . $item_inner . '</li>';
						}
					}
					$columns = min( 4, max( 1, $grid_limit ) );
					$children = '<ul class="products columns-' . $columns . ' ctb-product-grid">' . $grid_items . '</ul>';
				}
				$index = $template_start_index + $template_block_count;
			} elseif ( 'form' === $block['type'] ) {
				$submission = isset( $attributes['data-submission'] ) ? $attributes['data-submission'] : 'native';
				if ( 'external' === $submission && ! empty( $attributes['data-external-shortcode'] ) ) {
					$shortcode = trim( $attributes['data-external-shortcode'] );
					$allowed_shortcodes = array( 'contact-form-7', 'wpforms', 'formidable', 'gravityform', 'ninja_form' );
					$shortcode_pattern = '/^' . get_shortcode_regex( $allowed_shortcodes ) . '$/s';
					if ( preg_match( $shortcode_pattern, $shortcode, $shortcode_match ) && in_array( strtolower( $shortcode_match[2] ), $allowed_shortcodes, true ) ) {
						$children = do_shortcode( $shortcode );
					} else {
						$children = '<p class="ctb-form-external-note">External form: ' . esc_html( $shortcode ) . '</p>';
					}
					// External plugins render their own form; avoid invalid nested form markup.
					$tag = 'div';
					$attributes['class'] = trim( $attributes['class'] . ' ctb-form-external' );
				} else {
					// Native form: render children fields + honeypot + timestamp + submit
					$fields_html = '';
					foreach ( $block['children'] as $child ) {
						$child = self::object_to_array( $child );
						if ( isset( $child['kind'] ) && 'text' === $child['kind'] ) {
							$fields_html .= Code_To_Block_Shortcodes::render_text( $child['value'], $post_id );
						} else {
							$fields_html .= self::render_block( $child, $index, $post_id );
						}
					}
					$honeypot_name = '_ctb_hp_' . substr( md5( $block['id'] ), 0, 8 );
					$timestamp = time();
					$action_url = rest_url( 'code-to-block/v1/forms/' . (int) $post_id . '/submit' );
					$email_to = isset( $attributes['data-email-to'] ) ? $attributes['data-email-to'] : get_option( 'admin_email' );
					$submission_token = Code_To_Block_Forms::create_submission_token( $post_id, $block['id'], $timestamp );
					$children = '<div class="ctb-form-fields">' . $fields_html . '</div>'
						. '<div style="position:absolute;left:-9999px;top:auto;width:1px;height:1px;overflow:hidden;" aria-hidden="true"><label>Leave this field empty<input type="text" name="' . esc_attr( $honeypot_name ) . '" tabindex="-1" autocomplete="off"></label></div>'
						. '<input type="hidden" name="_ctb_form_id" value="' . esc_attr( $block['id'] ) . '">'
						. '<input type="hidden" name="_ctb_timestamp" value="' . esc_attr( $timestamp ) . '">'
						. '<input type="hidden" name="_ctb_submission_token" value="' . esc_attr( $submission_token ) . '">'
						. '<input type="hidden" name="_ctb_honeypot_name" value="' . esc_attr( $honeypot_name ) . '">'
						. '<div class="ctb-form-actions"><button type="submit" class="ctb-form-submit">Submit</button></div>'
						. '<div class="ctb-form-message" role="status" aria-live="polite" style="margin-top:12px;"></div>';
					// Wrap with form tag attributes
					$attributes['method'] = 'post';
					$attributes['action'] = $action_url;
					if ( strpos( $fields_html, 'type="file"' ) !== false ) {
						$attributes['enctype'] = 'multipart/form-data';
					}
					$attributes['class'] = trim( ( isset( $attributes['class'] ) ? $attributes['class'] : '' ) . ' ctb-form' );
					$attributes['data-email-to'] = $email_to;
					$attributes['data-form-id'] = $block['id'];
				}
				unset( $attributes['data-email-to'] );
			} elseif ( 'form_field' === $block['type'] ) {
				$field_type = isset( $attributes['data-field-type'] ) ? $attributes['data-field-type'] : 'text';
				$field_label = isset( $attributes['data-field-label'] ) ? $attributes['data-field-label'] : '';
				$field_name = isset( $attributes['data-field-name'] ) ? $attributes['data-field-name'] : $block['id'];
				$field_placeholder = isset( $attributes['data-field-placeholder'] ) ? $attributes['data-field-placeholder'] : '';
				$field_required = ! empty( $attributes['data-field-required'] );
				$field_options = isset( $attributes['data-field-options'] ) ? $attributes['data-field-options'] : '';
				$required_attr = $field_required ? ' required aria-required="true"' : '';
				$label_html = $field_label ? '<label for="' . esc_attr( $block['id'] . '-input' ) . '">' . esc_html( $field_label ) . ( $field_required ? ' <span aria-hidden="true">*</span>' : '' ) . '</label>' : '';
				if ( 'textarea' === $field_type ) {
					$children = $label_html . '<textarea id="' . esc_attr( $block['id'] . '-input' ) . '" name="' . esc_attr( $field_name ) . '" placeholder="' . esc_attr( $field_placeholder ) . '"' . $required_attr . ' rows="4"></textarea>';
				} elseif ( 'select' === $field_type ) {
					$options = array_map( 'trim', explode( ',', $field_options ) );
					$options_html = '<option value="">' . esc_html( $field_placeholder ? $field_placeholder : 'Select...' ) . '</option>';
					foreach ( $options as $opt ) {
						if ( '' === $opt ) continue;
						$options_html .= '<option value="' . esc_attr( $opt ) . '">' . esc_html( $opt ) . '</option>';
					}
					$children = $label_html . '<select id="' . esc_attr( $block['id'] . '-input' ) . '" name="' . esc_attr( $field_name ) . '"' . $required_attr . '>' . $options_html . '</select>';
				} elseif ( 'checkbox' === $field_type || 'radio' === $field_type ) {
					$options = array_map( 'trim', explode( ',', $field_options ) );
					if ( empty( $options[0] ) ) $options = array( $field_label ? $field_label : 'Option' );
					$group_html = '';
					foreach ( $options as $opt ) {
						if ( '' === $opt ) continue;
						$group_html .= '<label style="display:flex;gap:6px;align-items:center;"><input type="' . esc_attr( $field_type ) . '" name="' . esc_attr( $field_name ) . ( 'checkbox' === $field_type ? '[]' : '' ) . '" value="' . esc_attr( $opt ) . '"' . $required_attr . '> ' . esc_html( $opt ) . '</label>';
					}
					$children = ( $field_label && count( $options ) > 1 ? '<fieldset><legend>' . esc_html( $field_label ) . '</legend>' . $group_html . '</fieldset>' : $group_html );
				} elseif ( 'file' === $field_type ) {
					$children = $label_html . '<input id="' . esc_attr( $block['id'] . '-input' ) . '" type="file" name="' . esc_attr( $field_name ) . '"' . $required_attr . '>';
				} else {
					$type = in_array( $field_type, array( 'text', 'email', 'tel', 'url', 'number' ), true ) ? $field_type : 'text';
					$children = $label_html . '<input id="' . esc_attr( $block['id'] . '-input' ) . '" type="' . esc_attr( $type ) . '" name="' . esc_attr( $field_name ) . '" placeholder="' . esc_attr( $field_placeholder ) . '"' . $required_attr . '>';
				}
				$children = '<div class="ctb-form-field" data-field-type="' . esc_attr( $field_type ) . '">' . $children . '</div>';
			} elseif ( $is_dynamic && 'img' !== $tag ) {
				$dynamic_data = self::get_dynamic_data( $block['dynamic_source'], $post_id );
				$children = $dynamic_data['html'] ?? '';
			} else {
				$child_context_post_id = $post_id;

				foreach ( $block['children'] as $child ) {
					$child = self::object_to_array( $child );
					if ( isset( $child['kind'] ) && 'text' === $child['kind'] ) {
						$children .= ! empty( $block['is_content_slot'] ) && 'rich_text' === ( $block['slot_content_type'] ?? '' )
							? Code_To_Block_Schema::sanitize_rich_text( $child['value'] )
							: Code_To_Block_Shortcodes::render_text( $child['value'], $child_context_post_id );
					} else {
						$children .= self::render_block( $child, $index, $child_context_post_id );
					}
				}
			}
		} catch ( Throwable $error ) {
			if ( ! $is_saved_component ) {
				throw $error;
			}
			$children = esc_html( Code_To_Block_Components::FAILURE_MESSAGE );
		}

		// Some specialized blocks finalize their tag or attributes while rendering.
		$attribute_html = self::render_attributes( $tag, $attributes );
		return '<' . $tag . $attribute_html . '>' . $children . '</' . $tag . '>';
	}

	/**
	 * Applies WordPress-native login and role visibility rules.
	 *
	 * @param array $block Sanitized block.
	 * @return bool
	 */
	private static function block_is_visible( $block ) {
		$conditions = isset( $block['visibility_conditions'] ) ? self::object_to_array( $block['visibility_conditions'] ) : array();
		if ( empty( $conditions ) ) {
			return true;
		}
		$logged_in = function_exists( 'is_user_logged_in' ) && is_user_logged_in();
		if ( isset( $conditions['login'] ) ) {
			if ( 'logged_in' === $conditions['login'] && ! $logged_in ) {
				return false;
			}
			if ( 'logged_out' === $conditions['login'] && $logged_in ) {
				return false;
			}
		}
		if ( ! empty( $conditions['roles'] ) ) {
			if ( ! $logged_in || ! function_exists( 'wp_get_current_user' ) ) {
				return false;
			}
			$user_roles = (array) wp_get_current_user()->roles;
			if ( empty( array_intersect( $conditions['roles'], $user_roles ) ) ) {
				return false;
			}
		}
		return true;
	}

	/**
	 * @param string $source Dynamic source key.
	 * @param int    $post_id Context post ID.
	 * @return array
	 */
	private static function get_dynamic_data( $source, $post_id ) {
		$data = array( 'html' => '', 'url' => '', 'srcset' => '', 'alt' => '' );
		if ( strpos( $source, 'wc_product_' ) === 0 && function_exists( 'wc_get_product' ) ) {
			if ( ! in_array( get_post_type( $post_id ), array( 'product', 'product_variation' ), true ) ) {
				return $data;
			}
			$wc_product = wc_get_product( $post_id );
			if ( ! $wc_product ) {
				return $data;
			}
			switch ( $source ) {
				case 'wc_product_title':
					$data['html'] = esc_html( $wc_product->get_name() );
					break;
				case 'wc_product_price':
					$data['html'] = wp_kses_post( $wc_product->get_price_html() );
					break;
				case 'wc_product_short_description':
					$data['html'] = wp_kses_post( apply_filters( 'woocommerce_short_description', $wc_product->get_short_description() ) );
					break;
				case 'wc_product_stock_status':
					$data['html'] = wp_kses_post( wc_get_stock_html( $wc_product ) );
					if ( '' === trim( wp_strip_all_tags( $data['html'] ) ) ) {
						$data['html'] = esc_html( $wc_product->is_in_stock() ? 'In stock' : 'Out of stock' );
					}
					break;
				case 'wc_product_image':
					$image_id = $wc_product->get_image_id();
					if ( $image_id ) {
						$data['url'] = wp_get_attachment_image_url( $image_id, 'full' );
						$data['srcset'] = wp_get_attachment_image_srcset( $image_id, 'full' );
						$data['alt'] = get_post_meta( $image_id, '_wp_attachment_image_alt', true );
						if ( '' === $data['alt'] ) {
							$data['alt'] = wp_strip_all_tags( $wc_product->get_name() );
						}
					}
					break;
				default:
					if ( strpos( $source, 'wc_custom_field_' ) === 0 ) {
						$key = substr( $source, strlen( 'wc_custom_field_' ) );
						$data['html'] = esc_html( $wc_product->get_meta( $key ) );
					}
					break;
			}
		}
		return $data;
	}

	public static function get_woocommerce_block_markup( $name ) {
		$path = dirname( __DIR__ ) . '/templates/woocommerce-' . $name . '-block.html';
		if ( ! is_readable( $path ) ) {
			return '';
		}
		$markup = file_get_contents( $path );
		if ( ! is_string( $markup ) ) {
			return '';
		}
		// Render Interactivity API blocks
		return function_exists( 'do_blocks' ) ? do_blocks( $markup ) : $markup;
	}

	private static function count_rendered_blocks( $children ) {
		$count = 0;
		foreach ( $children as $child ) {
			$child = self::object_to_array( $child );
			if ( isset( $child['kind'] ) ) {
				continue;
			}
			++$count;
			$count += self::count_rendered_blocks( isset( $child['children'] ) ? $child['children'] : array() );
		}
		return $count;
	}

	/**
	 * @param array $block Sanitized block.
	 * @return array
	 */
	private static function runtime_actions_for_block( $block ) {
		$runtime_actions = array();
		foreach ( isset( $block['actions'] ) ? $block['actions'] : array() as $action ) {
			$normalized = Code_To_Block_Schema::normalize_runtime_action( $action );
			if ( null !== $normalized ) {
				$runtime_actions[] = $normalized;
			}
		}
		return $runtime_actions;
	}

	private static function animation_actions_for_block( $block ) {
		$animations = array();
		foreach ( isset( $block['actions'] ) ? $block['actions'] : array() as $action ) {
			$normalized = Code_To_Block_Schema::normalize_animation_action( $action );
			if ( null !== $normalized ) {
				$animations[] = $normalized;
			}
		}
		return $animations;
	}

	private static function css_animation_actions_for_block( $block ) {
		$animations = array();
		foreach ( isset( $block['actions'] ) ? $block['actions'] : array() as $action ) {
			$normalized = Code_To_Block_Schema::normalize_css_animation_action( $action );
			if ( null !== $normalized ) {
				$animations[] = $normalized;
			}
		}
		return $animations;
	}

	/**
	 * @param string $tag        HTML tag.
	 * @param array  $attributes Attribute map.
	 * @return string
	 */
	private static function render_attributes( $tag, $attributes ) {
		$rendered = '';

		if ( isset( $attributes['target'] ) && is_string( $attributes['target'] ) && '_blank' === strtolower( trim( $attributes['target'] ) ) ) {
			$attributes['target'] = '_blank';
			$rel_tokens = isset( $attributes['rel'] ) && is_string( $attributes['rel'] )
				? preg_split( '/\s+/', trim( $attributes['rel'] ) )
				: array();
			$rel_tokens = array_map( 'strtolower', $rel_tokens );
			$attributes['rel'] = implode( ' ', array_unique( array_filter( array_merge( array( 'noopener', 'noreferrer' ), $rel_tokens ) ) ) );
		}

		foreach ( $attributes as $name => $value ) {
			$name = strtolower( $name );
			if ( ! Code_To_Block_Schema::attribute_is_allowed( $tag, $name ) || false === $value ) {
				continue;
			}
			if ( true === $value ) {
				$rendered .= ' ' . esc_attr( $name );
				continue;
			}
			if ( ! is_string( $value ) ) {
				continue;
			}

			if ( in_array( $name, array( 'href', 'src', 'cite' ), true ) ) {
				$value = esc_url( self::normalize_resource_url( $value ) );
				if ( '' === $value ) {
					continue;
				}
				$rendered .= ' ' . esc_attr( $name ) . '="' . $value . '"';
				continue;
			}
			$rendered .= ' ' . esc_attr( $name ) . '="' . esc_attr( $value ) . '"';
		}

		return $rendered;
	}

	/**
	 * @param array $block   Sanitized block.
	 * @param int   $post_id Owning post ID.
	 * @param int   $index   Traversal index.
	 * @param array $rules   Collected rules.
	 */
	private static function collect_css_rules( $block, $post_id, &$index, &$rules ) {
		$current_index = $index++;
		$selector      = '#ctb-page-' . $post_id . ' .ctb-block-' . $current_index;
		self::append_rule( $rules['base'], $selector, $block['styles'] );
		$css_animations = self::css_animation_actions_for_block( $block );
		if ( ! empty( $css_animations ) && $css_animations[0]['params']['target_block_id'] === $block['id'] ) {
			$params = $css_animations[0]['params'];
			$rules['base'][] = sprintf(
				'%1$s{--ctb-reveal-y:%2$spx;--ctb-reveal-duration:%3$ss;--ctb-reveal-delay:%4$ss;}',
				$selector,
				(float) $params['from_y'],
				(float) $params['duration'],
				(float) $params['delay']
			);
		}

		$states = isset( $block['states'] ) ? self::object_to_array( $block['states'] ) : array();
		foreach ( array( 'hover', 'focus', 'active' ) as $state ) {
			if ( isset( $states[ $state ] ) ) {
				self::append_rule( $rules['base'], $selector . ':' . $state, $states[ $state ] );
			}
		}

		$responsive = isset( $block['responsive_overrides'] ) ? self::object_to_array( $block['responsive_overrides'] ) : array();
		foreach ( array( 'tablet', 'mobile' ) as $viewport ) {
			if ( isset( $responsive[ $viewport ] ) ) {
				self::append_rule( $rules[ $viewport ], $selector, $responsive[ $viewport ] );
			}
		}

		$is_saved_component = isset( $block['meta']['saved_component_id'] );
		try {
			foreach ( $block['children'] as $child ) {
				$child = self::object_to_array( $child );
				if ( ! isset( $child['kind'] ) ) {
					self::collect_css_rules( $child, $post_id, $index, $rules );
				}
			}
		} catch ( Throwable $error ) {
			if ( ! $is_saved_component ) {
				throw $error;
			}
		}
	}

	/**
	 * @param array $block    Sanitized block.
	 * @param array $snapshot Collected declarations keyed by block ID and context.
	 */
	private static function collect_style_snapshot( $block, &$snapshot ) {
		$block_id = isset( $block['id'] ) ? $block['id'] : '';
		$styles   = array( 'base' => isset( $block['styles'] ) ? $block['styles'] : null );

		$states = isset( $block['states'] ) ? self::object_to_array( $block['states'] ) : array();
		foreach ( array( 'hover', 'focus', 'active' ) as $state ) {
			if ( isset( $states[ $state ] ) ) {
				$styles[ $state ] = $states[ $state ];
			}
		}

		$responsive = isset( $block['responsive_overrides'] ) ? self::object_to_array( $block['responsive_overrides'] ) : array();
		foreach ( array( 'tablet', 'mobile' ) as $viewport ) {
			if ( isset( $responsive[ $viewport ] ) ) {
				$styles[ $viewport ] = $responsive[ $viewport ];
			}
		}

		foreach ( $styles as $context => $style ) {
			$declarations = self::style_declarations( $style );
			if ( '' !== $block_id && '' !== $declarations ) {
				$snapshot[ $block_id ][ $context ] = $declarations;
			}
		}

		foreach ( isset( $block['children'] ) ? $block['children'] : array() as $child ) {
			$child = self::object_to_array( $child );
			if ( ! isset( $child['kind'] ) ) {
				self::collect_style_snapshot( $child, $snapshot );
			}
		}
	}

	/**
	 * @param array  $rules    Destination list.
	 * @param string $selector Scoped selector.
	 * @param mixed  $style    Style set.
	 */
	private static function append_rule( &$rules, $selector, $style ) {
		$declarations = self::style_declarations( $style );
		if ( '' !== $declarations ) {
			$rules[] = $selector . '{' . $declarations . '}';
		}
	}

	/**
	 * @param mixed $style Style set.
	 * @return string
	 */
	private static function style_declarations( $style ) {
		$style = self::object_to_array( $style );
		if ( ! is_array( $style ) ) {
			return '';
		}

		$mapped      = isset( $style['mapped'] ) ? self::object_to_array( $style['mapped'] ) : array();
		$declarations = '';
		foreach ( $mapped as $property => $value ) {
			if ( ! is_string( $value ) || ! Code_To_Block_Schema::css_property_value_is_safe( $property, $value ) ) {
				continue;
			}
			$value         = preg_replace( '/\s*!important\s*$/i', '', trim( $value ) );
			$value         = self::normalize_css_urls( $value );
			$declarations .= $property . ':' . $value . '!important;';
		}

		$fallback = isset( $style['custom_css_fallback'] ) ? trim( $style['custom_css_fallback'] ) : '';
		if ( '' !== $fallback && Code_To_Block_Schema::css_declaration_list_is_safe( $fallback ) ) {
			$declarations .= rtrim( $fallback, ';' ) . ';';
		}

		return $declarations;
	}

	/**
	 * @param mixed $design_tokens Sanitized document token registry.
	 * @return string
	 */
	private static function design_token_declarations( $design_tokens ) {
		$design_tokens = self::object_to_array( $design_tokens );
		$declarations  = '';
		foreach ( Code_To_Block_Schema::TOKEN_CATEGORIES as $category ) {
			$tokens = isset( $design_tokens[ $category ] ) ? self::object_to_array( $design_tokens[ $category ] ) : array();
			foreach ( $tokens as $id => $token ) {
				$token = self::object_to_array( $token );
				$name  = Code_To_Block_Schema::design_token_css_name( $category . '.' . $id );
				$value = isset( $token['value'] ) && is_string( $token['value'] ) ? $token['value'] : '';
				if ( '' === $name || '' === $value || ! Code_To_Block_Schema::css_property_value_is_safe( $name, $value ) ) {
					continue;
				}
				$declarations .= $name . ':' . self::normalize_css_urls( trim( $value ) ) . ';';
			}
		}
		return $declarations;
	}

	/**
	 * Resolves relative imported resources consistently in admin and frontend.
	 *
	 * @param string $url Resource URL.
	 * @return string
	 */
	private static function normalize_resource_url( $url ) {
		$url = trim( $url );
		if ( '' === $url || preg_match( '#^(?:[a-z][a-z0-9+.-]*:|//|/|\#)#i', $url ) ) {
			return $url;
		}

		return trailingslashit( home_url() ) . ltrim( $url, '/' );
	}

	/**
	 * @param string $value CSS declaration value.
	 * @return string
	 */
	private static function normalize_css_urls( $value ) {
		return preg_replace_callback(
			'/url\(\s*(["\']?)([^"\')]+)\1\s*\)/i',
			function ( $matches ) {
				$quote = $matches[1];
				return 'url(' . $quote . self::normalize_resource_url( $matches[2] ) . $quote . ')';
			},
			$value
		);
	}

	/**
	 * @param int         $post_id          Owning post ID.
	 * @param array       $document         Sanitized block document.
	 * @param bool        $create_directory Whether to create the asset directory.
	 * @param string|null $css              Pre-generated stylesheet.
	 * @return array|WP_Error
	 */
	private static function get_asset_location( $post_id, $document, $create_directory, $css = null ) {
		$uploads = wp_upload_dir();
		if ( ! empty( $uploads['error'] ) ) {
			return self::filesystem_error( $uploads['error'] );
		}

		$directory = trailingslashit( $uploads['basedir'] ) . self::ASSET_DIRECTORY;
		if ( $create_directory && ! is_dir( $directory ) ) {
			if ( ! wp_mkdir_p( $directory ) ) {
				return self::filesystem_error( 'The stylesheet directory could not be created.' );
			}
		}
		
		if ( $create_directory ) {
			$htaccess_path = trailingslashit( $directory ) . '.htaccess';
			if ( ! file_exists( $htaccess_path ) ) {
				$htaccess_content = "<IfModule mod_expires.c>\n\tExpiresActive On\n\tExpiresByType text/css \"access plus 1 year\"\n</IfModule>\n<IfModule mod_headers.c>\n\t<FilesMatch \"\.css$\">\n\t\tHeader set Cache-Control \"public, max-age=31536000, immutable\"\n\t</FilesMatch>\n</IfModule>\n";
				@file_put_contents( $htaccess_path, $htaccess_content );
			}
		}

		if ( null === $css ) {
			$css = self::generate_css( $document, $post_id );
		}
		$filename = 'ctb-page-' . (int) $post_id . '-' . substr( hash( 'sha256', $css ), 0, 16 ) . '.css';
		return array(
			'directory' => $directory,
			'path'      => trailingslashit( $directory ) . $filename,
			'url'       => trailingslashit( $uploads['baseurl'] ) . self::ASSET_DIRECTORY . '/' . $filename,
		);
	}

	/**
	 * @param string $message Error detail.
	 * @return WP_Error
	 */
	private static function filesystem_error( $message ) {
		return new WP_Error(
			'code_to_block_css_write_failed',
			$message,
			array( 'status' => 500 )
		);
	}

	/**
	 * @param mixed $value Potential object.
	 * @return mixed
	 */
	private static function object_to_array( $value ) {
		return is_object( $value ) ? get_object_vars( $value ) : $value;
	}
}
