export const WIDGET_LIBRARY = [
	{
		id: 'widget-pricing-table',
		label: 'Pricing Table',
		description: 'Three-column pricing with slots for price and features',
		block: {
			id: 'widget-pricing-root',
			type: 'container',
			tag: 'section',
			attributes: { class: 'ctb-widget-pricing' },
			children: [
				{
					id: 'widget-pricing-title',
					type: 'text',
					tag: 'h2',
					attributes: {},
					children: [ { kind: 'text', value: 'Starter' } ],
					styles: {
						mapped: { 'font-size': '20px', 'font-weight': '700' },
						custom_css_fallback: '',
					},
					meta: { source: 'widget-library' },
					is_content_slot: true,
					slot_label: 'Plan Name',
					slot_content_type: 'text',
				},
				{
					id: 'widget-pricing-price',
					type: 'text',
					tag: 'p',
					attributes: { class: 'price' },
					children: [ { kind: 'text', value: '$19/mo' } ],
					styles: {
						mapped: { 'font-size': '32px' },
						custom_css_fallback: '',
					},
					meta: { source: 'widget-library' },
					is_content_slot: true,
					slot_label: 'Price',
					slot_content_type: 'text',
				},
				{
					id: 'widget-pricing-features',
					type: 'container',
					tag: 'ul',
					attributes: {},
					children: [
						{
							id: 'widget-pricing-f1',
							type: 'text',
							tag: 'li',
							attributes: {},
							children: [
								{ kind: 'text', value: 'Feature one' },
							],
							styles: { mapped: {}, custom_css_fallback: '' },
							meta: { source: 'widget-library' },
							is_content_slot: true,
							slot_label: 'Feature 1',
							slot_content_type: 'text',
						},
						{
							id: 'widget-pricing-f2',
							type: 'text',
							tag: 'li',
							attributes: {},
							children: [
								{ kind: 'text', value: 'Feature two' },
							],
							styles: { mapped: {}, custom_css_fallback: '' },
							meta: { source: 'widget-library' },
							is_content_slot: true,
							slot_label: 'Feature 2',
							slot_content_type: 'text',
						},
					],
					styles: { mapped: {}, custom_css_fallback: '' },
					meta: { source: 'widget-library' },
				},
				{
					id: 'widget-pricing-cta',
					type: 'button',
					tag: 'a',
					attributes: { href: '#', class: 'ctb-cta' },
					children: [ { kind: 'text', value: 'Get Started' } ],
					styles: {
						mapped: {
							background: '#6558d3',
							color: '#fff',
							padding: '10px 16px',
							'border-radius': '6px',
						},
						custom_css_fallback: '',
					},
					meta: { source: 'widget-library' },
					is_content_slot: true,
					slot_label: 'CTA Text',
					slot_content_type: 'link',
				},
			],
			styles: {
				mapped: {
					border: '1px solid #ddd',
					'border-radius': '12px',
					padding: '24px',
					'max-width': '320px',
				},
				custom_css_fallback: 'display:grid;gap:12px;',
			},
			meta: { source: 'widget-library' },
		},
	},
	{
		id: 'widget-testimonial',
		label: 'Testimonial Card',
		description: 'Quote with avatar and attribution',
		block: {
			id: 'widget-testimonial-root',
			type: 'container',
			tag: 'figure',
			attributes: { class: 'ctb-widget-testimonial' },
			children: [
				{
					id: 'widget-testimonial-img',
					type: 'image',
					tag: 'img',
					attributes: { src: '', alt: 'Avatar' },
					children: [],
					styles: {
						mapped: {
							'border-radius': '50%',
							width: '48px',
							height: '48px',
						},
						custom_css_fallback: '',
					},
					meta: { source: 'widget-library' },
					is_content_slot: true,
					slot_label: 'Avatar Image',
					slot_content_type: 'image',
				},
				{
					id: 'widget-testimonial-quote',
					type: 'text',
					tag: 'blockquote',
					attributes: {},
					children: [
						{
							kind: 'text',
							value: 'This product changed our business.',
						},
					],
					styles: {
						mapped: { 'font-size': '16px' },
						custom_css_fallback: '',
					},
					meta: { source: 'widget-library' },
					is_content_slot: true,
					slot_label: 'Quote',
					slot_content_type: 'text',
				},
				{
					id: 'widget-testimonial-name',
					type: 'text',
					tag: 'figcaption',
					attributes: {},
					children: [ { kind: 'text', value: 'Alex Rivera' } ],
					styles: {
						mapped: { 'font-weight': '700' },
						custom_css_fallback: '',
					},
					meta: { source: 'widget-library' },
					is_content_slot: true,
					slot_label: 'Attribution',
					slot_content_type: 'text',
				},
			],
			styles: {
				mapped: {
					background: '#fffbeb',
					padding: '20px',
					'border-radius': '12px',
					border: '1px solid #f59e0b',
				},
				custom_css_fallback: '',
			},
			meta: { source: 'widget-library' },
		},
	},
	{
		id: 'widget-icon-box',
		label: 'Icon Box',
		description: 'Icon with title and description',
		block: {
			id: 'widget-iconbox-root',
			type: 'container',
			tag: 'div',
			attributes: { class: 'ctb-widget-iconbox' },
			children: [
				{
					id: 'widget-iconbox-icon',
					type: 'text',
					tag: 'div',
					attributes: { class: 'icon', 'aria-hidden': 'true' },
					children: [ { kind: 'text', value: '★' } ],
					styles: {
						mapped: { 'font-size': '32px' },
						custom_css_fallback: '',
					},
					meta: { source: 'widget-library' },
				},
				{
					id: 'widget-iconbox-title',
					type: 'text',
					tag: 'h3',
					attributes: {},
					children: [ { kind: 'text', value: 'Feature Title' } ],
					styles: {
						mapped: { 'font-size': '18px', 'font-weight': '700' },
						custom_css_fallback: '',
					},
					meta: { source: 'widget-library' },
					is_content_slot: true,
					slot_label: 'Title',
					slot_content_type: 'text',
				},
				{
					id: 'widget-iconbox-desc',
					type: 'text',
					tag: 'p',
					attributes: {},
					children: [
						{
							kind: 'text',
							value: 'Short description of the feature.',
						},
					],
					styles: {
						mapped: { 'font-size': '14px' },
						custom_css_fallback: '',
					},
					meta: { source: 'widget-library' },
					is_content_slot: true,
					slot_label: 'Description',
					slot_content_type: 'text',
				},
			],
			styles: {
				mapped: {
					padding: '16px',
					border: '1px solid #e5e7eb',
					'border-radius': '8px',
					'text-align': 'center',
				},
				custom_css_fallback: 'display:grid;gap:8px;',
			},
			meta: { source: 'widget-library' },
		},
	},
	{
		id: 'widget-countdown',
		label: 'Countdown Timer',
		description: 'Static countdown display (JS can be added via actions)',
		block: {
			id: 'widget-countdown-root',
			type: 'container',
			tag: 'div',
			attributes: { class: 'ctb-widget-countdown' },
			children: [
				{
					id: 'widget-countdown-label',
					type: 'text',
					tag: 'p',
					attributes: {},
					children: [ { kind: 'text', value: 'Sale ends in:' } ],
					styles: {
						mapped: { 'font-size': '14px' },
						custom_css_fallback: '',
					},
					meta: { source: 'widget-library' },
				},
				{
					id: 'widget-countdown-time',
					type: 'text',
					tag: 'div',
					attributes: { class: 'ctb-countdown-time' },
					children: [ { kind: 'text', value: '02:14:33' } ],
					styles: {
						mapped: {
							'font-size': '28px',
							'font-weight': '700',
							'letter-spacing': '0.05em',
						},
						custom_css_fallback: '',
					},
					meta: { source: 'widget-library' },
					is_content_slot: true,
					slot_label: 'Time Display',
					slot_content_type: 'text',
				},
			],
			styles: {
				mapped: {
					background: '#171d35',
					color: '#fff',
					padding: '16px',
					'border-radius': '8px',
					'text-align': 'center',
				},
				custom_css_fallback: '',
			},
			meta: { source: 'widget-library' },
		},
	},
	{
		id: 'widget-stats',
		label: 'Stats / Counter',
		description: 'Large number with label',
		block: {
			id: 'widget-stats-root',
			type: 'container',
			tag: 'div',
			attributes: { class: 'ctb-widget-stats' },
			children: [
				{
					id: 'widget-stats-number',
					type: 'text',
					tag: 'div',
					attributes: { class: 'ctb-stat-number' },
					children: [ { kind: 'text', value: '1,200+' } ],
					styles: {
						mapped: { 'font-size': '36px', 'font-weight': '700' },
						custom_css_fallback: '',
					},
					meta: { source: 'widget-library' },
					is_content_slot: true,
					slot_label: 'Number',
					slot_content_type: 'text',
				},
				{
					id: 'widget-stats-label',
					type: 'text',
					tag: 'p',
					attributes: {},
					children: [ { kind: 'text', value: 'Happy customers' } ],
					styles: {
						mapped: { 'font-size': '14px' },
						custom_css_fallback: '',
					},
					meta: { source: 'widget-library' },
					is_content_slot: true,
					slot_label: 'Label',
					slot_content_type: 'text',
				},
			],
			styles: {
				mapped: {
					padding: '16px',
					'text-align': 'center',
					border: '1px solid #e5e7eb',
					'border-radius': '8px',
				},
				custom_css_fallback: '',
			},
			meta: { source: 'widget-library' },
		},
	},
	{
		id: 'widget-team',
		label: 'Team Member',
		description: 'Photo, name, role, bio',
		block: {
			id: 'widget-team-root',
			type: 'container',
			tag: 'div',
			attributes: { class: 'ctb-widget-team' },
			children: [
				{
					id: 'widget-team-photo',
					type: 'image',
					tag: 'img',
					attributes: { src: '', alt: 'Team member' },
					children: [],
					styles: {
						mapped: {
							'border-radius': '50%',
							width: '80px',
							height: '80px',
						},
						custom_css_fallback: '',
					},
					meta: { source: 'widget-library' },
					is_content_slot: true,
					slot_label: 'Photo',
					slot_content_type: 'image',
				},
				{
					id: 'widget-team-name',
					type: 'text',
					tag: 'h3',
					attributes: {},
					children: [ { kind: 'text', value: 'Jordan Lee' } ],
					styles: {
						mapped: { 'font-size': '18px', 'font-weight': '700' },
						custom_css_fallback: '',
					},
					meta: { source: 'widget-library' },
					is_content_slot: true,
					slot_label: 'Name',
					slot_content_type: 'text',
				},
				{
					id: 'widget-team-role',
					type: 'text',
					tag: 'p',
					attributes: { class: 'role' },
					children: [ { kind: 'text', value: 'Founder' } ],
					styles: {
						mapped: { 'font-size': '14px', color: '#6b7280' },
						custom_css_fallback: '',
					},
					meta: { source: 'widget-library' },
					is_content_slot: true,
					slot_label: 'Role',
					slot_content_type: 'text',
				},
				{
					id: 'widget-team-bio',
					type: 'text',
					tag: 'p',
					attributes: {},
					children: [
						{ kind: 'text', value: 'Short bio goes here.' },
					],
					styles: {
						mapped: { 'font-size': '14px' },
						custom_css_fallback: '',
					},
					meta: { source: 'widget-library' },
					is_content_slot: true,
					slot_label: 'Bio',
					slot_content_type: 'text',
				},
			],
			styles: {
				mapped: {
					padding: '16px',
					'text-align': 'center',
					border: '1px solid #e5e7eb',
					'border-radius': '12px',
				},
				custom_css_fallback: 'display:grid;gap:8px;place-items:center;',
			},
			meta: { source: 'widget-library' },
		},
	},
	{
		id: 'widget-faq',
		label: 'FAQ Accordion',
		description: 'Question and answer (expand via toggle action)',
		block: {
			id: 'widget-faq-root',
			type: 'container',
			tag: 'div',
			attributes: { class: 'ctb-widget-faq' },
			children: [
				{
					id: 'widget-faq-q',
					type: 'text',
					tag: 'h3',
					attributes: {},
					children: [
						{ kind: 'text', value: 'What is your return policy?' },
					],
					styles: {
						mapped: { 'font-size': '16px', 'font-weight': '700' },
						custom_css_fallback: '',
					},
					meta: { source: 'widget-library' },
					is_content_slot: true,
					slot_label: 'Question',
					slot_content_type: 'text',
				},
				{
					id: 'widget-faq-a',
					type: 'text',
					tag: 'p',
					attributes: {},
					children: [
						{
							kind: 'text',
							value: 'You can return within 30 days for a full refund.',
						},
					],
					styles: {
						mapped: { 'font-size': '14px' },
						custom_css_fallback: '',
					},
					meta: { source: 'widget-library' },
					is_content_slot: true,
					slot_label: 'Answer',
					slot_content_type: 'text',
				},
			],
			styles: {
				mapped: {
					border: '1px solid #e5e7eb',
					'border-radius': '8px',
					padding: '16px',
				},
				custom_css_fallback: '',
			},
			meta: { source: 'widget-library' },
		},
	},
	{
		id: 'widget-gallery',
		label: 'Image Gallery Grid',
		description: '3-image grid with slots',
		block: {
			id: 'widget-gallery-root',
			type: 'container',
			tag: 'div',
			attributes: { class: 'ctb-widget-gallery' },
			children: [
				{
					id: 'widget-gallery-1',
					type: 'image',
					tag: 'img',
					attributes: { src: '', alt: 'Gallery 1' },
					children: [],
					styles: {
						mapped: {
							width: '100%',
							height: 'auto',
							'border-radius': '6px',
						},
						custom_css_fallback: '',
					},
					meta: { source: 'widget-library' },
					is_content_slot: true,
					slot_label: 'Image 1',
					slot_content_type: 'image',
				},
				{
					id: 'widget-gallery-2',
					type: 'image',
					tag: 'img',
					attributes: { src: '', alt: 'Gallery 2' },
					children: [],
					styles: {
						mapped: {
							width: '100%',
							height: 'auto',
							'border-radius': '6px',
						},
						custom_css_fallback: '',
					},
					meta: { source: 'widget-library' },
					is_content_slot: true,
					slot_label: 'Image 2',
					slot_content_type: 'image',
				},
				{
					id: 'widget-gallery-3',
					type: 'image',
					tag: 'img',
					attributes: { src: '', alt: 'Gallery 3' },
					children: [],
					styles: {
						mapped: {
							width: '100%',
							height: 'auto',
							'border-radius': '6px',
						},
						custom_css_fallback: '',
					},
					meta: { source: 'widget-library' },
					is_content_slot: true,
					slot_label: 'Image 3',
					slot_content_type: 'image',
				},
			],
			styles: {
				mapped: {},
				custom_css_fallback:
					'display:grid;grid-template-columns:repeat(3,1fr);gap:12px;',
			},
			meta: { source: 'widget-library' },
		},
	},
];

export function getWidget( id ) {
	return WIDGET_LIBRARY.find( ( w ) => w.id === id ) || null;
}
